<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Tipo de Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux=null;
			
Ext.onReady(function(){


			aux = buscarId();
			
				delete Ext.tip.Tip.prototype.minWidth;

					Ext.define('actividadTipo', {
						extend: 'Ext.data.Model',
						fields: [
							{
								type: 'int',
								name: 'act_actividad_tipo_id'
							},{
								type: 'string',
								name: 'titulo'
							},{
								type: 'string',
								name: 'modalidad'
							}
						]
					});
                                        
                                        var si_no = Ext.create('Ext.data.Store', {
                                        fields: ['id', 'nombre'],
                                        data : [
					        {"id": "S", "nombre":"Si"},
					        {"id": "N" , "nombre":"No"}
				        ]
					});

					Ext.define('anhoFormacion', {
						extend: 'Ext.data.Model',
						fields: [
							{
								type: 'int',
								name: 'cal_anho_formacion_id'
							},{
								type: 'string',
								name: 'anho'
							}
						]
					});

					Ext.define('moneda', {
						extend: 'Ext.data.Model',
						fields: [
							{
								type: 'int',
								name: 'cont_moneda_id'
							},{
								type: 'string',
								name: 'nombre'
							}
						]
					});
					
                                        Ext.define('ciclo', {
						extend: 'Ext.data.Model',
						fields: [
							{
								type: 'int',
								name: 'act_ciclo_id'
							},{
								type: 'string',
								name: 'nombre'
							}
						]
					});
                                        
                                        Ext.define('posiblesFormadores', {
						extend: 'Ext.data.Model',
						fields: [
							{
								type: 'int',
								name: 'org_parte_rol_id'
							},{
								type: 'int',
								name: 'org_parte_id'
							},{
								type: 'string',
								name: 'nombre'
							},{
								type: 'string',
								name: 'apellido'
							},{
					            name: 'mostrar', 
					            convert: function (v, rec) {
					               return rec.get('nombre') + ', ' + rec.get('apellido');
					            }
					        }
						]
					});
                                        
                                        var posiblesFormadoresStore = Ext.create('Ext.data.Store', {
					model: 'posiblesFormadores',
					proxy: {
						type: 'ajax',
						extraParams: {'s[actividad]':aux, 's[tipo]':'formador'},
						headers: {'Accept':'application/json'},
						url: baseURL + '/actividad/actividad/listar-partes',
						reader: {
							type: 'json',
							root: 'records'
						}
					},
					autoLoad: true
                                        });
                                        
					var actividadTipoStore = Ext.create('Ext.data.Store', {
						model: 'actividadTipo',
						proxy: {
							type: 'ajax',
							extraParams: {'p[limit]':'all','relacion_ayuda': 'S'},
							headers: {'Accept':'application/json'},
							url: baseURL + '/actividad/combos/act-actividad-tipo',
							reader: {
								type: 'json',
								root: 'records'
							}
						}
					});
                                        

					var anhoFormacionStore = Ext.create('Ext.data.Store', {
						model: 'anhoFormacion',
						proxy: {
							type: 'ajax',
							extraParams: {'p[limit]':'all'},
							headers: {'Accept':'application/json'},
							url: baseURL + '/actividad/combos/cal-anho-formacion',
							reader: {
								type: 'json',
								root: 'records'
							}
						},
						autoLoad: true
					});

					var monedaStore = Ext.create('Ext.data.Store', {
						model: 'moneda',
						proxy: {
							type: 'ajax',
							extraParams: {'p[limit]':'all'},
							headers: {'Accept':'application/json'},
							url: baseURL + '/actividad/combos/cont-moneda',
							reader: {
								type: 'json',
								root: 'records'
							}
						},
						autoLoad: true
					});
                                        
                                        var cicloStore = Ext.create('Ext.data.Store', {
						model: 'ciclo',
						proxy: {
							type: 'ajax',
							extraParams: {'p[limit]':'all'},
							headers: {'Accept':'application/json'},
							url: baseURL + '/actividad/combos/act-ciclo',
							reader: {
								type: 'json',
								root: 'records'
							}
						},
                                                autoLoad: true
					});
					
                                        
                                        
					var buttonCrear = function(b,e)
					{
									var basicForm = b.up('form').getForm();
							if(basicForm.isValid())
							{
								            var valoresForm = basicForm.getFieldValues();
		
									Ext.Ajax.request({
										   url: baseURL + '/actividad/actividad/post',
										   success: function(response, opt){
											   var aux_mensaje = Ext.decode(response.responseText);
											   aux = aux_mensaje['act_actividad_id'];
											   Ext.Msg.show({
												    title:'Aviso',
													msg:'Actividad Creada Correctamente'
											   });
											   function hide_message() {
											       Ext.defer(function() {
											           Ext.MessageBox.hide();
										       }, delay);
											   var url = baseURL+'/actividad/actividad/get-ui#?id='+aux;  
							                   window.location = url;
										   }
										   hide_message();										   
										   
									   },
										failure: function(response, opt){
											   var aux_mensaje = Ext.decode(response.responseText);
											   var mensaje = " ";
												   for (error in aux_mensaje.datos) {
					                            		mensaje = mensaje +"- "+ error +": "+aux_mensaje.datos[error]+'<br>';  
					                                }
												Ext.MessageBox.show({
						                            title: aux_mensaje.mensaje,
						                            msg: mensaje,
						                            icon: Ext.MessageBox.ERROR,
						                            buttons: Ext.Msg.OK
						                        });
										},
									   jsonData:{
									       'post':{
										       'Actividad':{
												   'titulo': 'Relaci&oacute;n Ayuda',
												   'act_actividad_tipo_id': valoresForm.act_actividad_tipo_id,
                                                                                                   'act_ciclo_id': valoresForm.act_ciclo_id,
												   'duracion': valoresForm.duracion,
												   'monto_referencial': valoresForm.monto,
												   'cont_moneda_id': valoresForm.cont_moneda_id,
                                                                                                   'requiere_certificado': 'N',
												   'nro_personas': 1,
												   'cal_anho_formacion_id': valoresForm.cal_anho_formacion_id,
												   'fecha_inicio': (formatearFecha(valoresForm.fecha, 1)),
												   'fecha_fin': (formatearFecha(valoresForm.fecha, 1)),
												   'observaciones': valoresForm.observaciones
										       },
                                                                                       'Participantes':[{
                                                                                                    'act_actividad_participantes_id': "new_id",
                                                                                                    'org_parte_rol_id': valoresForm.org_parte_rol_id,
                                                                                                    'es_principal': "S"
                                                                                                    }
											    ]	
									       }
									   }
								 });
							}
							else
							{
								Ext.Msg.alert('Aviso','Hay campos inv&aacute;lidos');
								return;
							}  	
						
						
					};

					
				var panelActividad = Ext.create('Ext.form.Panel', {
					items:[{
					    xtype: 'panel',
					    bodyStyle: {
				        	background: '#C8CED8',
				        },
					    title: 'Actividad',
					    //anchor:'90%',
					    height: 'fit',
					    width: 'fit',
					    border: 1,
					//    flex: 1,
					    padding: 10,
					    layout: 'hbox',
					    defaultType: 'textfield',
					    items: [{
							xtype: 'container',
							flex: 1,
							layout: 'anchor',
							defaultType: 'textfield',
							items: [{
                                                                        fieldLabel: 'Tipo de Act',
                                                                        xtype: 'combobox',
                                                                        forceSelection: true,
                                                                        labelWidth: 110,
                                                                        tabIndex: 2,
                                                                        store: actividadTipoStore,
                                                                        displayField: 'titulo',
                                                                        queryMode: 'local',
                                                                        valueField: 'act_actividad_tipo_id',
                                                                        allowBlank: false,
                                                                        padding: 15,
                                                                        anchor:'90%',
                                                                        id : 'act_actividad_tipo_id',
                                                                        name: 'act_actividad_tipo_id'
                                                            },{
								    	fieldLabel: 'Costo',
								    	labelWidth: 110,
								    	xtype: 'numberfield',
								    	minValue: 0,
								    	tabIndex: 5,
								    	hideTrigger: true,
								    	anchor:'90%',
								    	padding: 15,
								    	name: 'monto',
                                                            },{
								    	fieldLabel: 'Duraci&oacute;n (hs.)',
								    	labelWidth: 110,
								    	xtype: 'numberfield',
								    	minValue: 0,
								    	value: 0,
								    	step: 0.25,
								    	tabIndex: 3,
								    	anchor:'90%',
								    	padding: 15,
								    	name: 'duracion',
                                                            },{
                                                                        fieldLabel: 'Fecha',
                                                                        xtype: 'datefield',
                                                                        format: 'd/m/Y',
                                                                        tabIndex: 9,
                                                                        padding: 15,
                                                                        labelWidth: 110,
                                                                        anchor:'90%',
                                                                        name: 'fecha' 
                                                            }
					    	]},{
					    		xtype: 'container',
				                flex: 1,
				                layout: 'anchor',
				                defaultType: 'textfield',
				                items: [{
							    	fieldLabel: 'Ciclo',
							    	xtype: 'combobox',
                                                                forceSelection: true,
							        labelWidth: 110,
							        tabIndex: 4,
							        store: cicloStore,
							        displayField: 'nombre',
							        queryMode: 'local',
							        valueField: 'act_ciclo_id',
							        allowBlank: false,
							        padding: 15,
						 	        anchor:'90%',
                                                                id: 'act_ciclo_id',
							        name: 'act_ciclo_id'
                                                    },{
							        fieldLabel: 'Moneda',
							        xtype: 'combobox',
							        forceSelection: true,
							        labelWidth: 110,
							        store: monedaStore,
							        displayField: 'nombre',
							        queryMode: 'local',
							        valueField: 'cont_moneda_id',
							        allowBlank: false,
							        padding: 15,
							        tabIndex: 6,
						 	        anchor:'90%',
						 	        name: 'cont_moneda_id',
                                                    },{
                                                                fieldLabel: 'A&ntilde;o de Form.',
                                                                xtype: 'combobox',
                                                                forceSelection: true,
                                                                labelWidth: 110,
                                                                store: anhoFormacionStore,
                                                                displayField: 'anho',
                                                                queryMode: 'local',
                                                                valueField: 'cal_anho_formacion_id',
                                                                allowBlank: false,
                                                                padding: 15,
                                                                tabIndex: 7,
                                                                anchor:'90%',
                                                                name: 'cal_anho_formacion_id'  
                                                    }]
					    	}]},{
                                            items:[{
                                                xtype: 'panel',
                                                bodyStyle: {
                                                    background: '#C8CED8',
                                            },
				 	    title: 'Datos del Participante',
					    //anchor:'90%',
					    height: 'fit',
					    width: 'fit',
					    border: 1,
					//    flex: 1,
					    padding: 10,
					    layout: 'hbox',
					    defaultType: 'textfield',
					    items: [{
							xtype: 'container',
							flex: 1,
							layout: 'anchor',
							defaultType: 'textfield',
							items: [{

								    	fieldLabel: 'Sobrenombre',
								    	xtype: 'combobox',
								    	forceSelection: false,
								        labelWidth: 110,
                                                                        width: 500,
								        store: posiblesFormadoresStore,
								        displayField: 'mostrar',
								        queryMode: 'remote',
								        valueField: 'org_parte_rol_id',
								        allowBlank: false,
								        padding: 15,
								        tabIndex: 12,
							 	        anchor:'90%',
								    	name: 'org_parte_rol_id',                                                                                                                    
								        typeAhead: true,								        
								        loadingText: 'Buscando...',
								        hideTrigger: true,
								        queryParam: 's[parte]',
								        minChars: 1,
                                                        },{
                                                                        fieldLabel: 'Observaci&oacute;n',
                                                                        xtype: 'textarea',
                                                                        padding: 15,
                                                                        tabIndex: 11,
                                                                        labelWidth: 110,
                                                                        anchor:'190%',
                                                                        name: 'observaciones', 
                                                                
                                                            }
					    	]},{
							xtype: 'container',
							flex: 1,
							layout: 'anchor',
							defaultType: 'textfield',
							items: [{

								    	fieldLabel: 'Monto Pagado',
								    	labelWidth: 110,
								    	xtype: 'numberfield',
								    	minValue: 0,
								    	tabIndex: 5,
								    	hideTrigger: true,
								    	anchor:'90%',
								    	padding: 15,
								    	name: 'precio',
                                                        }
					    	]}
					    	]
					    
				     }]},{
				    	xtype: 'container',
				 	    height: 200,
				 	    width: 'fit',
				 	   layout: 'hbox',
				 	    items:[
						  { xtype: 'tbfill' },	
				 	      {	  
				 	    	  xtype: 'button',
				 	    	  margin: '5 0 15 0',
						      scale: 'large',
						      width: 100, 
						      text: 'Guardar',
							  //disabled: true,
							  handler: buttonCrear
				 	      },{
				 	    	  xtype: 'button',
				 	    	  margin: '5 15 15 20',
				 	    	  width: 100, 
						      scale: 'large',
						      text: 'Cancelar',
							  //disabled: true,
							  handler: function() {
								  window.location = baseURL+'/actividad/actividad/index-ui';
							}
				 	      }
					    ]
				     }]
					});

					
				var pantalla = Ext.create('Ext.form.Panel', {
					 type:  'hbox',			 
					 width: 'fit',
					 height: 'fit',		           
					 items:[panelActividad],
					  listeners:{
								'render':function(){
										Ext.getCmp('topTabPanel').setActiveTab(1);
//										Ext.getCmp('actividadTabPanel').setActiveTab(0);
                                                                                actividadTipoStore.load({
                                                                                    callback: function(records, operation, success) {
                                                                                                 var aux = actividadTipoStore.getAt(0).get('act_actividad_tipo_id');
                                                                                                 Ext.getCmp('act_actividad_tipo_id').setValue(aux);
                                                                                    }
                                                                                });
                                                                                 
								}
					  }	    	
				});
												
				Ext.getCmp('centerPanel').add(pantalla);
																			
});

			
		</script>
    </head>
    <body>
    </body>
</html>