<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;


		var cargarDatos = function (){
			aux = buscarId();
			Ext.Ajax.request({
			    url: baseURL +'/actividad/relacion-ayuda/get',
			    params: {
			        'id': aux,
			    },
			    success: function(response) {
	                
			    	var campos = Ext.decode(response.responseText);
			    	var form = Ext.getCmp('form').getForm();
			    	
			    	for (campo in campos) {
				    	
				    	var name = form.findField(campo);
				    		if (name) {
				    			if (campo == "fecha_inicio")
						    	{
				    				if (campos[campo]){
							    		var fecha = campos[campo];
					 			    	var fecha2 = fecha.split("-");
					 			    	var result = fecha2[2]+'-'+fecha2[1]+'-'+fecha2[0];
					 			    	campos[campo] = result;
					 			    	name.setValue(campos[campo]);
				    				}
						    	 }else {								    
									    	name.setValue(campos[campo]);
							     }
					    }	}	
			    	}
				});
		};
		
		var pantallaActividad = Ext.create('Ext.form.Panel', {
			id: 'form',
			items:[{
			    xtype: 'panel',
			    bodyStyle: {
		        	background: '#C8CED8',
		        },
			    title: 'Datos de la Actividad',
			    height: 210,
			    width: 'fit',
			    border: 1,
			    padding: 10,
			    layout: 'hbox',
			    defaultType: 'textfield',
			    items: [{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'displayfield',
					items: [    
					    {
						        fieldLabel: 'Tipo',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'titulo',
						},{
						        fieldLabel: 'Costo Referencial',
						        padding: 15,
						        labelWidth: 140,
						        anchor:'90%',
					 	        name: 'precio',
			    	 	 },{
						    	fieldLabel: 'Fecha',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						    	name: 'fecha_inicio',
				   	 	}
			    	]},{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'displayfield',
					items: [{
				    	        fieldLabel: 'Tipo de Actividad',
						        padding: 15,
						        labelWidth: 140,
						        anchor:'90%',
						        name: 'actividad_tipo'
				    	 },{
						    	fieldLabel: 'A&ntilde;o de Formaci&oacute;n',
						        padding: 15,
						        labelWidth: 140,
						        anchor:'90%',
						        name: 'anho_formacion',	  
				    	 },{
						        fieldLabel: 'Observaci&oacute;n',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'observaciones',
				   	 	 }
                                                        
			    	]},{
			    		xtype: 'container',
		                flex: 1.5,
		                layout: 'anchor',
		                defaultType: 'displayfield',
		                items: [{
					    		 	fieldLabel: 'Formador',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'formador',
							  },{
					    		 	fieldLabel: 'Duraci&oacute;n',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'duracion',
							  }
			    		]
			    	}]},{
					    xtype: 'panel',
					    bodyStyle: {
				        	background: '#C8CED8',
				        },
					    title: 'Datos de la Persona',
					    height: 150,
					    width: 'fit',
					    border: 1,
					    padding: '0 10 10 10',
					    layout: 'hbox',
					    defaultType: 'textfield',
					    items: [{
							xtype: 'container',
							flex: 1,
							layout: 'anchor',
							defaultType: 'displayfield',
							items: [    
							   {
								        fieldLabel: 'Identificador',
								        padding: 15,
								        labelWidth: 110,
								        anchor:'90%',
								        name: 'identificador',
						   	 	},{
								        fieldLabel: 'Descripci&oacute;n',
								        padding: 15,
								        labelWidth: 110,
								        anchor:'90%',
								        name: 'descripcion',
					   	 	 }
					    	]},{
							xtype: 'container',
							flex: 1,
							layout: 'anchor',
							defaultType: 'displayfield',
							items: [{
								        fieldLabel: 'Sobrenombre',
								        padding: 15,
								        labelWidth: 110,
								        anchor:'90%',
								        name: 'alias',
						   	 	}
		                                                        
					    	]},{
					    		xtype: 'container',
				                flex: 1.5,
				                layout: 'anchor',
				                defaultType: 'displayfield',
				                items: [{
						    		 	fieldLabel: 'Monto Pagado',
								        padding: 15,
								        labelWidth: 110,
								        anchor:'90%',
								        name: 'monto_participante',
				                }
					    		]
					    	}]}],
			});
	
		var pantalla = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 
			 width: 'fit',
			 height: 'fit',		           
			 items:[
								{
									xtype: 'panel',
									height: 360,
								    width: 'fit',
									//style:'background-color: #C8CED8',
									//layout: 'fit',
									items: [pantallaActividad]
								},{
							    	xtype: 'container',
							 	    height: 200,
							 	    width: 'fit',
							 	   layout: 'hbox',
							 	   // flex: 1,
							 	   // padding: '5 0 10 440',
							 	    items:[
									  { xtype: 'tbfill' },
							 	      {
							 	    	  xtype: 'button',
							 	    	  margin: '5 15 15 20',
									      scale: 'large',
									      width: 100,
									      text: 'Volver',
										  //disabled: true,
										  handler: function() {
											  window.location = baseURL+'/actividad/relacion-ayuda/index-ui';
										}
							 	      }
								    ]
							     }
								
			  ],
			  listeners:{
						'render':function(){
								Ext.getCmp('topTabPanel').setActiveTab(1);
//								Ext.getCmp('actividadTabPanel').setActiveTab(1);
						}
			  }	    	
		});

		cargarDatos();
		Ext.getCmp('centerPanel').add(pantalla);
});

			
		</script>
    </head>
    <body>
    </body>
</html>
