<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Personas</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux;
			var prof;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('personas', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'org_parte_id'
				},
				{
					type: 'string',
					name: 'org_parte_tipo_codigo'
				}
				,
				{
					type: 'string',
					name: 'nombre_organizacion'
				},
				{
					type: 'string', 
					name: 'nombre_persona'
				},
				{
					type: 'string', 
					name: 'apellido_persona'
				},{
					type: 'string', 
					name: 'fecha_nacimiento'
				},{
					type: 'string', 
					name: 'genero_persona'
				},{
					type: 'png', 
					name: 'foto'
				},{
					type: 'string', 
					name: 'org_parte_tipo_nombre'
				},{
					type: 'object', 
					name: 'documentos'
				}
			]
		});

		
		var personasStore = Ext.create('Ext.data.Store', {
			model: 'personas',
			pageSize: itemsPorPagina, 
			proxy: {
				type: 'ajax',
				  extraParams:{
				    	"p[limit]": itemsPorPagina,
						"p[page]": page, 
				  },
				headers: {'Accept':'application/json'},
				url: baseURL + '/org/personas/index?format=json',
				reader: {
					type: 'json',
					root: 'records',
					totalProperty: 'numResults'
				}
			},
			autoLoad: true
		});

		var buscarId = function(){
			if (window.location.hash) {
			    var params = (window.location.hash.substr(1)).split("#");
			        var id = params[0].split("=");
					return id[1];
			}
		};

		var crearDoc = function (valor, tipo, origen)
		{			
			var aux_valor = Ext.create('Ext.form.DisplayField', {
				fieldLabel: 'Nro. de Doc',
    	    	labelWidth: 90,
    	        allowBlank: false,
    	        value: valor,
    	        padding: 15,
    	        anchor:'90%',
			});

			var aux_tipo = Ext.create('Ext.form.DisplayField', {
				fieldLabel: 'Tipo de Doc',
		        width: 350,
		        labelWidth: 95,
		        value: tipo,
		        padding: 15,
		        anchor:'90%',
			});

			var aux_origen = Ext.create('Ext.form.DisplayField', {
				fieldLabel: 'Origen de Doc',
		        labelWidth: 110,
		        width: 350,
		        value: origen,
		        padding: 15,
	 	        anchor:'90%',
			});

			Ext.getCmp('doc_nro').add(aux_valor);
			Ext.getCmp('doc_tipo').add(aux_tipo);
			Ext.getCmp('doc_origen').add(aux_origen);
			
		};

		var crearUbic = function (direccion, lugar)
		{			
			var aux_direccion = Ext.create('Ext.form.DisplayField', {
				fieldLabel: 'Direcci&oacute;n',
		        allowBlank: true,
		        value: direccion,
		        padding: 15,
		        anchor:'90%',
			});

			var aux_lugar = Ext.create('Ext.form.DisplayField', {
				fieldLabel: 'Barrio',
		        labelWidth: 60,
		        value: lugar,
		        padding: 15,
		        anchor:'90%',
			});

			Ext.getCmp('ubic_direccion').add(aux_direccion);
			Ext.getCmp('ubic_lugar').add(aux_lugar);
			
		};

		var crearCont = function (tipo, contacto)
		{			
			var aux_tipo = Ext.create('Ext.form.DisplayField', {
				fieldLabel: 'Tipo de Contacto',
		        labelWidth: 130,
		        value: tipo,
		        padding: 15,
	 	        anchor:'90%',
			});

			var aux_contacto = Ext.create('Ext.form.DisplayField', {
				fieldLabel: 'Contacto',
			    labelWidth: 70,
			    anchor:'90%',
			    value: contacto,
			    padding: 15,
			});

			Ext.getCmp('cont_tipo').add(aux_tipo);
			Ext.getCmp('cont_contacto').add(aux_contacto);
			
		};
		var cargarDatos = function (){
			aux = buscarId();
			Ext.Ajax.request({
			    url: baseURL +'/org/parte/get?id=int',
			    params: {
			        'id': aux,
			    },
			    success: function(response) {
			    	var campos = Ext.decode(response.responseText);
			    	var form = Ext.getCmp('form').getForm();		    	
			    	for (campo in campos) {
				    	if (campo == "documentos"){
							var docs = (campos[campo]);
								for (doc in docs) {
									if(doc){
										var valor = (docs[doc].valor);
										var tipo = (docs[doc].org_documento_tipo);
										var origen = (docs[doc].dir_pais);
										crearDoc(valor, tipo, origen);
									}							
								}
								continue;
			    		}
			    		if (campo == "Direcciones"){
							var ubics = (campos[campo]);
							for (ubic in ubics) {
								if(ubic){
									var direccion = (ubics[ubic].direccion);
									var lugar = (ubics[ubic].dir_barrio);
									crearUbic(direccion, lugar);
								}							
							}
							continue;	
		    			}
			    		if (campo == "contactos"){
							var conts = (campos[campo]);
							for (cont in conts) {
								if(cont){
									var tipo = (conts[cont].org_contacto_tipo);
									var contacto = (conts[cont].contacto);
									crearCont(tipo, contacto);
								}							
							}
							continue;	
		    			}	
				    	var name = form.findField(campo);
				    		if (name) {
						    	if (campo == "fecha_nacimiento")
						    	{
						    		var fecha = campos["fecha_nacimiento"];
				 			    	var fecha2 = fecha.split("-");
				 			    	var result = fecha2[2]+'-'+fecha2[1]+'-'+fecha2[0];
				 			    	campos[campo] = result;
				 			    	name.setValue(campos[campo]);
				 			    	console.log(campos[campo]);
							    }else if (campo == "genero_persona")
						    	{
							    	if (campos[campo] == 'M'){
							    		campos[campo] = 'Masculino';
							    	}	
							    	else if (campos[campo] == 'F'){
							    		campos[campo] = 'Femenino';
							    	}
				 			    		name.setValue(campos[campo]);
							    } else if (campo == "Profesiones")
						    	{
							    	var profs = (campos[campo]);
						    		prof = profs[0].profesion;
						    		name.setValue(prof);
							    } else{
							    
								    	name.setValue(campos[campo]);
								    	//console.log(campo);
						    	}	
						    }	
			    	}
			    }
			});
		};

				var panelPersona = Ext.create('Ext.form.Panel', {
					id: 'form',
					items:[{
					    xtype: 'panel',
					    id: 'panelDoc',
					    title: 'Datos de Documentaci&oacute;n',
					    bodyStyle: {
				     		background: '#C8CED8',
				      	},
					    collapsible: true,
					    height: 'fit',
					    width: 'fit',
					    border: 1,
					    padding: 10,
					    layout: 'hbox',
						 items: [{
									xtype: 'container',
									id: 'doc_nro',
									flex: 1,
									defaultType: 'displayfield',
									layout: 'anchor',
									items: []
							   },{
									xtype: 'container',
									flex: 1,
									id: 'doc_tipo',
									defaultType: 'displayfield',
									layout: 'anchor',
									items: []
							   },{
									xtype: 'container',
									id: 'doc_origen',
									flex: 1,
									defaultType: 'displayfield',
									layout: 'anchor',
									items: []}
					    	    ]},{
					    xtype: 'panel',
					    title: 'Datos Personales',
					    bodyStyle: {
				     		background: '#C8CED8',
				      	},
					    collapsible: true,
					    height: 'fit',
					    width: 'fit',
					    border: 1,
					    padding: '0 10 10 10',
					    layout: 'hbox',
					    items: [{
							xtype: 'container',
							flex: 1,
							defaultType: 'displayfield',
							layout: 'anchor',
							items: [    
							    {
								        fieldLabel: 'Nombres',
								        padding: 15,
								        labelWidth: 110,
								        anchor:'90%',
								        name: 'nombre_persona'
							    },{
							        	fieldLabel: 'Fecha de Nac:',
							        	labelWidth: 110,
							 	        padding: 15,
							 	        anchor:'90%',
							 	        name: 'fecha_nacimiento'
				         		},{
								    	fieldLabel: 'Profesi&oacute;n',							    	
								        labelWidth: 110,
								        padding: 15,
							 	        anchor:'90%',
								        name: 'Profesiones',	  
					    	    }
					    	]},{
					    		xtype: 'container',
				                flex: 1,
				                layout: 'anchor',
				                defaultType: 'displayfield',
				                items: [{
						    	        fieldLabel: 'Apellidos',
						    	        labelWidth: 110,
						    	        padding: 15,
								        anchor:'90%',
								        name: 'apellido_persona'
					    	    },{
								        fieldLabel: 'Estado Civil',
								        labelWidth: 110,
								        padding: 15,
								        anchor:'90%',
								        name: 'estado_civil',
								},{
								        fieldLabel: 'Religi&oacute;n',
								        labelWidth: 110,
								        padding: 15,
							 	        anchor:'90%',
							 	        name: 'religion',
								}
					    		]
					    	},{
					    		xtype: 'container',
				                flex: 1,
				                layout: 'anchor',
				                defaultType: 'displayfield',
				                items: [{
								        fieldLabel: 'Nacionalidad',
								        labelWidth: 110,
								        padding: 15,
							 	        anchor:'90%',
							 	        name: 'nacionalidad_persona', 
					    	    },{
							        	 padding: 15,
							             fieldLabel: 'Genero',
							             labelWidth: 110,
									     padding: 15,
								 	     anchor:'90%',
										 name: 'genero_persona',
						         },{
								    	fieldLabel: 'Nro. de hijos',
								    	labelWidth: 110,
								    	anchor:'90%',
								    	padding: 15,
								    	name: 'nro_hijos',
						    	 }
					    		]
					    	}]},{
					    xtype: 'panel',
					    id: 'panelUbic',
					    bodyStyle: {
				     		background: '#C8CED8',
				      	},
					    title: 'Datos de Ubicaci&oacute;n',
					    collapsible: true,
					    height: 'fit',
					    width: 'fit',
					    border: 1,
					    padding: '0 10 10 10',
					    layout: 'hbox',
						 items: [{
								xtype: 'container',
								flex: 1,
								id: 'ubic_direccion',
								defaultType: 'displayfield',
								layout: 'anchor',
								items: []
							},{
								xtype: 'container',
								flex: 1,
								id: 'ubic_lugar',
								defaultType: 'displayfield',
								layout: 'anchor',
								items: []}
					    	]},{
				    	xtype: 'panel',
					    title: 'Datos de Contacto',
					    bodyStyle: {
				     		background: '#C8CED8',
				      	},
					    id: 'panelCont',
					    collapsible: true,
					    height: 'fit',
					    width: 'fit',
					    border: 1,
					    padding: '0 10 10 10',
					    layout: 'hbox',
				        items: [{
									xtype: 'container',
									flex: 1,
									id: 'cont_tipo',
									defaultType: 'displayfield',
									layout: 'anchor',
									items: []
						    	},{        
									xtype: 'container',
									flex: 1,
									defaultType: 'displayfield',
									id: 'cont_contacto',
									layout: 'anchor',
									items: []    
							    }
						]
				     },{
				    	xtype: 'container',
				 	    height: 'fit',
				 	    width: 'fit',
				 	    layout: 'hbox',
				 	    items:[
						  { xtype: 'tbfill' },	
				 	      {	  
				 	    	  xtype: 'button',
				 	    	  margin: '5 0 15 0',
				 	    	  width: 100, 
						      scale: 'large',
						      text: 'Editar',
						      handler: function() {
						    	  var url = baseURL+'/org/personas/editar-ui#?id='+aux;  
			                   	  window.location = url;
						      }
				 	      },{
				 	    	  xtype: 'button',
				 	    	  margin: '5 15 15 20',
				 	    	  width: 100,
						      scale: 'large',
						      text: 'Volver',
							  handler: function() {
								  window.location = baseURL+'/org/personas/index-ui';
						      }
				 	      }
					    ]
				     }]
					});
		
		var pantalla = Ext.create('Ext.form.Panel', {
			//id: 'margen', 
		    //title: ' ',
		    width: 'fit',
		    height: 'fit',
		    renderTo: Ext.getBody(),
		    items:[panelPersona],
			listeners:{
				'render':function(){
					Ext.getCmp('topTabPanel').setActiveTab(0);
//					Ext.getCmp('personaTabPanel').setActiveTab(0);
				}
			}
		});	
		cargarDatos();
		Ext.getCmp('centerPanel').add(pantalla);
});

			
		</script>
    </head>
    <body>
    </body>
</html>
