<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Personas</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';
			var mensajes = '<?php echo $texto; ?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('personas', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'org_parte_id'
				},
				{
					type: 'string',
					name: 'org_parte_tipo'
				}
				,
				{
					type: 'string',
					name: 'nombre_organizacion'
				},
				{
					type: 'string', 
					name: 'nombre_persona'
				},
				{
					type: 'string', 
					name: 'apellido_persona'
				},{
					type: 'string', 
					name: 'fecha_nacimiento'
				},{
					type: 'png', 
					name: 'foto'
				},{
					type: 'string', 
					name: 'genero_persona'
				},{
					type: 'string', 
					name: 'org_parte_tipo_nombre'
				},{
					type: 'string', 
					name: 'documentos'
				}
			]
		});

		Ext.define('ComboPersonas', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: '__'
				},
				{
					type: 'string',
					name: 'nombre'
				}
			]
		});

// 		var ComboPersonasStore = Ext.create('Ext.data.Store', {
// 			model: 'ComboPersonas',
// 			pageSize: 10, 
// 			proxy: {
// 				type: 'ajax',
// 				extraParams: {'p[limit]':'10'},
// 				headers: {'Accept':'application/json'},
// 				url: baseURL + '/inscripciones/combos/pe-asignatura-prop?format=json',
// 				reader: {
// 					type: 'json',
// 					root: 'records',
// 					totalProperty: 'numResults',
// 				}
// 			},
// 			autoLoad: true
// 		});
		
		var personasStore = Ext.create('Ext.data.Store', {
			model: 'personas',
			pageSize: itemsPorPagina, 
			proxy: {
				type: 'ajax',
				  extraParams:{
				    	"p[limit]": itemsPorPagina,
						"p[page]": page, 
				  },
				headers: {'Accept':'application/json'},
				url: baseURL + '/org/personas/index?format=json',
				reader: {
					type: 'json',
					root: 'records',
					totalProperty: 'numResults'
				}
			},
			autoLoad: true
		});
	

		 var comboPersonas = Ext.create('Ext.form.field.ComboBox', {
		        fieldLabel: 'Buscar Persona',
		        displayField: 'nombre',
		        valueField: 'pe_asignatura_prop_id',
		        width: 370,
		        name: 'nombre',
		        labelWidth: 70,
		       // store: ComboPersonasStore,
		        queryMode: 'remote',
		        typeAhead: true,
		        emptyText: 'Escriba el nombre de la Persona...',
		        loadingText: 'Buscando Personas...',
		        hideTrigger: true,
		       // forceSelection: true,
		        queryParam: 's[nombre]:',
		        minChars: 2,
		  });
		  
		var gridPersonas = Ext.create('Ext.grid.Panel', {
            title: 'Personas',
            selModel: {
                checkOnly: true,
                injectCheckbox: 1
            },
            width: 'fit',
            padding: '0 20 0 20',
            height: 450,
            region: 'center',  
	           dockedItems: [{
                    xtype: 'pagingtoolbar',
                    store: personasStore, 
                    dock: 'bottom',
                    displayInfo: true,
                    listeners: {
                        'afterrender': function (component)
                        {
                            component.down('#refresh').hide()
                        },single: true
                    },
                    displayMsg: 'Cursos {0} al {1} de {2}',
                    beforePageText: 'P&aacute;gina',
                    afterPageText : 'de {0}',
                    moveNext : function(){ 
                   		page = page + itemsPorPagina;
                   	 	this.store.currentPage++;
           				personasStore.load({
	       				    params:{
	       				    	"p[limit]": itemsPorPagina,
	       						"p[page]": page,
	       						//"s[pe_plan_estudio_ver_id]": auxcarrera	        
	       				    }
       					});
           					console.log("page store: ", page);
          				    console.log("page extjs: ",this.store.currentPage);	
                	 },
                 	 movePrevious : function(){ 
                 		page = page - itemsPorPagina;
						this.store.currentPage--;
						personasStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   						//"s[pe_plan_estudio_ver_id]": auxcarrera	 	        
		   				    }
   						});
	       					console.log("page store: ", page);
	      				    console.log("page extjs: ",this.store.currentPage);	
            		 },
             		moveFirst : function(){ 
             			page = 0;
						this.store.currentPage = 1;
						personasStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   						//"s[pe_plan_estudio_ver_id]": auxcarrera	 	        
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);	
            	 	},
            	 	moveLast : function(){                 	 	
            	 		if (this.getStore().getTotalCount() % itemsPorPagina == "0"){
	                	 	page = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)-1)*itemsPorPagina;
	                	 	this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina));
            	 		}
						else
						{
							page = parseInt(this.getStore().getTotalCount() / itemsPorPagina)*itemsPorPagina;
							this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)+1);
						}
            	 		personasStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   					//	"s[pe_plan_estudio_ver_id]": auxcarrera	 		        
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);         					
            	 	},
                }],                       
            layout: 'fit',
            emptyText: "No existen personas",
            
            store: personasStore,
            loadMask: true,
            // grid columns
            columns:[{
                text: "Nombre",
                dataIndex: 'nombre_persona',
                sortable: true,
                align: 'center',
                flex: 1.5,
                renderer: function(val, metadata, record, otraCosa, otraCosaMas) {
                    console.log(metadata);
                    return '<a href="'+baseURL+'/org/parte/get?id=' + metadata.record.data.org_parte_id +'">'+ val +'</a>';
            	}
//	            renderer: function(v,meta,record){
//					return '<div class="viewIcon" onclick="verPersona(' + personasStore.getAt(0).get('prg_curso_id') + ')"></div>';
//				}
            },{
                text: "Apellido",
                dataIndex: 'apellido_persona',
                align: 'center',
                flex: 1,
            },{
                text: "Documento",
                dataIndex: 'documentos',
                align: 'center',
                flex: 1,
            },{
                text: "Fecha de Nacimiento",
                dataIndex: 'fecha_nacimiento',
                align: 'center',
                flex: 1,
            },{
                text: "Sexo",
                dataIndex: 'genero_persona',
                align: 'center',
                flex: 1,
            }
            ]
            	        	
		 });

		var pantallaPersonas = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 id: 'margen',
			    width: 'fit',	
			    renderTo: document.body,		           
			    items:[
				{
				    xtype: 'container',
				    id: 'filtros',
				    height: 55,
				    layout:'hbox',
				    items:[
						  {
							    xtype: 'container',
							    padding: '15 0 0 25',
							    flex: 1.15,
							    layout: 'anchor',
							    defaultType: 'textfield',
							    //items: [comboCarrera]
						  }
					   ]
					},{
						xtype: 'container',
					    height: 45,
					    layout:'hbox',
					    items:[{
			
				           		xtype: 'button',
				           		width: 100,
				           		margin: '0 0 0 20',
				            	text: 'Filtrar',
					            scale   : 'medium',
					            handler: function(b,e) {
					            	
							           var basicForm = b.up('form').getForm();						
							           var valoresForm = basicForm.getFieldValues();
					           
							         //  	auxcarrera = valoresForm.carrera;
			
										//inicializo los pages
//							           	page = 0;
//										gridPlan.store.currentPage = 1;
//						                planEstudioStore.load({
//											params: {
//												"s[pe_plan_estudio_ver_id]": auxcarrera	 		
//									   		} 
//						               });
						            }//end of handler  
									        
								},{
			
						  		xtype: 'button',
						  		width: 100,
						  		margin: '0 0 0 15',
			               		text: 'Limpiar',
				           		scale   : 'medium',
				           		handler: function(b,e) {
				           			//inicializo los pages
						           	page = 0;
									gridPersonas.store.currentPage = 1;
									//console.log(this);
				           			b.up('form').getForm().reset();
				           			personasStore.load();
							           			
				           		}
								}]},{
									xtype: 'container',
									layout: 'fit',  
						            items: [gridPersonas]  					
								}
				    	],			    	
		});

				
});

			
		</script>
    </head>
    <body>
    </body>
</html>
