<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Personas</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 90px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';
			var mensajes = '<?php echo $texto; ?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('cursos', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'prg_curso_id'
				},
				{
					type: 'string',
					name: 'codigo'
				}
				,
				{
					type: 'string',
					name: 'seccion'
				},
				{
					type: 'string', 
					name: 'turno'
				},
				{
					type: 'string', 
					name: 'asignatura'
				},{
					type: 'string', 
					name: 'codigo_asignatura'
				},{
					type: 'int', 
					name: 'anho'
				},{
					type: 'string', 
					name: 'semestre'
				},{
					type: 'string', 
					name: 'fecha_inscripcion'
				},{
					type: 'string', 
					name: 'porc_asistencia'
				}
			]
		});
		
		var cursosStore = Ext.create('Ext.data.Store', {
			model: 'cursos',
			pageSize: itemsPorPagina, 
			proxy: {
				type: 'ajax',
				  extraParams:{
				    	"p[limit]": itemsPorPagina,
						"p[page]": page,
						//"s[pe_plan_estudio_ver_id]": auxcarrera,  
				  },
				headers: {'Accept':'application/json'},
				url: baseURL + '/org/personas/index-ui?format=json',
				reader: {
					type: 'json',
					root: 'records',
					totalProperty: 'numResults'
				}
			},
			autoLoad: true
		});
	
		 
		var gridCursos = Ext.create('Ext.grid.Panel', {
            title: 'Mis Cursos',
            selModel: {
                checkOnly: true,
                injectCheckbox: 1
            },
            width: 'fit',
            padding: '0 20 0 20',
            height: 480,
            region: 'center',  
	           dockedItems: [{
                    xtype: 'pagingtoolbar',
                    store: cursosStore, 
                    dock: 'bottom',
                    displayInfo: true,
                    listeners: {
                        'afterrender': function (component)
                        {
                            component.down('#refresh').hide()
                        },single: true
                    },
                    displayMsg: 'Cursos {0} al {1} de {2}',
                    beforePageText: 'P&aacute;gina',
                    afterPageText : 'de {0}',
                    moveNext : function(){ 
                   		page = page + itemsPorPagina;
                   	 	this.store.currentPage++;
           				cursosStore.load({
	       				    params:{
	       				    	"p[limit]": itemsPorPagina,
	       						"p[page]": page,
	       						//"s[pe_plan_estudio_ver_id]": auxcarrera	        
	       				    }
       					});
           					console.log("page store: ", page);
          				    console.log("page extjs: ",this.store.currentPage);	
                	 },
                 	 movePrevious : function(){ 
                 		page = page - itemsPorPagina;
						this.store.currentPage--;
						cursosStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   						//"s[pe_plan_estudio_ver_id]": auxcarrera	 	        
		   				    }
   						});
	       					console.log("page store: ", page);
	      				    console.log("page extjs: ",this.store.currentPage);	
            		 },
             		moveFirst : function(){ 
             			page = 0;
						this.store.currentPage = 1;
						cursosStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   						//"s[pe_plan_estudio_ver_id]": auxcarrera	 	        
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);	
            	 	},
            	 	moveLast : function(){                 	 	
            	 		if (this.getStore().getTotalCount() % itemsPorPagina == "0"){
	                	 	page = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)-1)*itemsPorPagina;
	                	 	this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina));
            	 		}
						else
						{
							page = parseInt(this.getStore().getTotalCount() / itemsPorPagina)*itemsPorPagina;
							this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)+1);
						}
            	 		cursosStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   					//	"s[pe_plan_estudio_ver_id]": auxcarrera	 		        
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);         					
            	 	},
                }],                       
            layout: 'fit',
            emptyText: "No tiene cursos",
            
            store: cursosStore,
            loadMask: true,
            // grid columns
            columns:[{
                text: "Asignatura",
                dataIndex: 'asignatura',
                sortable: true,
                align: 'center',
                flex: 1.5,
                renderer: function(val, metadata, record, otraCosa, otraCosaMas) {
                    console.log(metadata);
                    return '<a href="'+baseURL+'/cursos/cursos/get-ui#' + metadata.record.data.prg_curso_id +'">'+ val +'</a>';
            	}
//	            renderer: function(v,meta,record){
//					return '<div class="viewIcon" onclick="verPersona(' + cursosStore.getAt(0).get('prg_curso_id') + ')"></div>';
//				}
            },{
                text: "C&oacute;digo",
                dataIndex: 'codigo_asignatura',
                align: 'center',
                flex: 0.5,
            },{
                text: "Secci&oacute;n",
                dataIndex: 'seccion',
                align: 'center',
                flex: 0.5,
            },{
                text: "Turno",
                dataIndex: 'turno',
                align: 'center',
                flex: 0.5,
            },{
                text: "A&ntilde;o",
                dataIndex: 'anho',
                align: 'center',
                flex: 0.5,
            },{
                text: "Semestre",
                dataIndex: 'semestre',
                align: 'center',
                flex: 0.6,
            },{
                text: "Fecha Inscripci&oacute;n",
                dataIndex: 'fecha_inscripcion',
                align: 'center',
                flex: 0.7,
            },{
                text: "Asistencia(%)",
                dataIndex: 'porc_asistencia',
                align: 'center',
                flex: 0.7,
            }
            ]
            	        	
		 });

		var pantallaCursos = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 id: 'margen',
			    width: 'fit',	
			    renderTo: document.body,		           
			    items:[
				{
				    xtype: 'container',
				    id: 'filtros',
				    height: 55,
				    layout:'hbox',
				    items:[
						  {
							    xtype: 'container',
							    padding: '15 0 0 25', //margen del Form 'arriba lateral abajo'
							//  width: 350,
							    flex: 1.15,
							    layout: 'anchor',
							    defaultType: 'textfield',
							 //   items: [comboCarrera]
						  }
					   ]
					},{
						xtype: 'container',
					    height: 45,
					    layout:'hbox',
					    items:[{
			
				           		xtype: 'button',
				           		width: 100,
				           		margin: '0 0 0 20',
				            	text: 'Filtrar',
					            scale   : 'medium',
					            handler: function(b,e) {
					            	
							           var basicForm = b.up('form').getForm();						
							           var valoresForm = basicForm.getFieldValues();
					           
							         //  	auxcarrera = valoresForm.carrera;
			
										//inicializo los pages
//							           	page = 0;
//										gridPlan.store.currentPage = 1;
//						                planEstudioStore.load({
//											params: {
//												"s[pe_plan_estudio_ver_id]": auxcarrera	 		
//									   		} 
//						               });
						            }//end of handler  
									        
								},{
			
						  		xtype: 'button',
						  		width: 100,
						  		margin: '0 0 0 15',
			               		text: 'Limpiar',
				           		scale   : 'medium',
				           		handler: function(b,e) {
				           			//inicializo los pages
						           	page = 0;
									gridCursos.store.currentPage = 1;
									//console.log(this);
				           			b.up('form').getForm().reset();
				           			cursosStore.load();
							           			
				           		}
								}]},{
									xtype: 'container',
									layout: 'fit',  
						            items: [gridCursos]  					
								}
				    	],			    	
		});

				
});

			
		</script>
    </head>
    <body>
    </body>
</html>
