<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux=null;
            var aux_org_parte_id = null;
			
Ext.onReady(function(){
		delete Ext.tip.Tip.prototype.minWidth;
		
			aux = buscarId();
                                
                                    
               
        Ext.define('aportes', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'ap_aporte_detalle_id'
				},{
					type: 'string',
					name: 'monto'
				},{
					type: 'string',
					name: 'moneda'
				},{
					type: 'string',
					name: 'fecha'
				},{
					type: 'string',
					name: 'tipo'
				},{
					type: 'string',
					name: 'rol_socio'
				},{
		            name: 'monto_moneda', 
		            convert: function (v, rec) {
		               return rec.get('monto') + ' ' + rec.get('moneda');
		            }
		        }
            ]
       });

                                        
        var aportesStore = Ext.create('Ext.data.Store', {
                model: 'aportes',
                proxy: {
                        type: 'ajax',
                        extraParams: {'id':aux_org_parte_id, 'p[limit]':'all'},
                        headers: {'Accept':'application/json'},
                        url: baseURL + '/aporte/aporte/list-aportes',
                        reader: {
                                type: 'json',
                                root: 'records'
                        }
                }
                //autoLoad: true
        });

		
		var cargarDatos = function (){
			Ext.Ajax.request({
			   	url: baseURL +'/aporte/aporte/getpersona',
				    params: {
				        'id': aux,
				    },
		    success: function(response) {
		    	var campos = Ext.decode(response.responseText);
		    	var form = Ext.getCmp('form').getForm();
		    	
		    	for (campo in campos) {
		    	    if (campo == "org_parte_id"){
                            aux_org_parte_id  = campos[campo];
                            aportesStore.load({params: {'id':aux_org_parte_id, 'p[limit]':'all'}});
                    }else if(campo == "roles"){
                    	var roles = campos[campo];              
                    	for (rol in roles) {
                    		var rol2 = roles[rol];
                    		//console.log(rol2['rol_socio']); 
                    		var name2 = form.findField('roles');
				    		if (name2){
				    			if (name2.getValue()== ""){         
									name2.setValue(rol2['rol_socio']);
								}else{
									name2.setValue(name2.getValue()+'  -  '+rol2['rol_socio']);
								}
				    		}
                    	}
                    }else{                       
				    	var name = form.findField(campo);
				    		if (name) {                                           
									    name.setValue(campos[campo]);
				    		}
				    }
			    }
			}
			   
			});
		};

				
				// var buttonEditar = function(b,e)
				// {
				// 				var basicForm = b.up('form').getForm();
				// 	if(basicForm.isValid())
				// 	{  						
			 //            var valoresForm = basicForm.getFieldValues();

				// 		Ext.Ajax.request({
				// 			   url: baseURL + '/actividad/actividad/put',
				// 			   success: function(response, opt){
				// 				   Ext.Msg.show({
				// 					    title:'Aviso',
				// 						msg:'Actividad Editada Correctamente'
				// 				   });
				// 				   function hide_message() {
				// 				       Ext.defer(function() {
				// 				           Ext.MessageBox.hide();
				// 				       }, delay);
				// 				   }
				// 				   hide_message();
				// 				   window.location = baseURL+'/actividad/actividad/index-ui';
				// 			   },
				// 				failure: function(response, opt){
				// 					   var aux_mensaje = Ext.decode(response.responseText);
				// 					   var mensaje = " ";
				// 						   for (error in aux_mensaje.datos) {
			 //                            		mensaje = mensaje +"- "+ error +": "+aux_mensaje.datos[error]+'<br>';  
			 //                                }
				// 						Ext.MessageBox.show({
				//                             title: aux_mensaje.mensaje,
				//                             msg: mensaje,
				//                             icon: Ext.MessageBox.ERROR,
				//                             buttons: Ext.Msg.OK
				//                         });
				// 				},
				// 			   jsonData:{
				// 			       'put':{
    //                                     'Actividad':{
    //                                                'act_actividad_id': aux,
    //                                                'titulo': valoresForm.titulo,
    //                                                'act_ciclo_id': valoresForm.act_ciclo_id,
    //                                                'act_actividad_tipo_id': valoresForm.act_actividad_tipo_id,
    //                                                'duracion': valoresForm.duracion,
    //                                                'monto_referencial': valoresForm.monto_referencial,
    //                                                'cont_moneda_id': valoresForm.cont_moneda_id,
    //                                                'requiere_certificado': valoresForm.requiere_certificado,
    //                                                'cal_anho_formacion_id': valoresForm.cal_anho_formacion_id,
    //                                                'fecha_inicio': (formatearFecha(valoresForm.fecha_inicio, 1)),
    //                                                'fecha_fin': (formatearFecha(valoresForm.fecha_fin, 1)),
    //                                                'observaciones': valoresForm.observaciones	
    //                                     },
    //                                     'Formadores':[{
    //                                                 'act_actividad_formadores_id': aux_formador_id,
    //                                                 'org_parte_rol_id': valoresForm.org_parte_rol_id,
    //                                                 'es_principal': "S"
    //                                                 }
    //                                     ]	
				// 			       }
				// 			   }
                                                                   
				// 		 });
				// 	}
				// 	else
				// 	{
				// 		Ext.Msg.alert('Aviso','Hay campos inv&aacute;lidos');
				// 		return;
				// 	}  	
					
				// };
				
		var pantallaActividad = Ext.create('Ext.form.Panel', {
			id: 'form',
			items:[{
			    xtype: 'panel',
			    bodyStyle: {
		        	background: '#C8CED8',
		        },
			    title: 'Datos del Socio',
			    //anchor:'90%',
			    height: 'fit',
			    width: 'fit',
			    border: 1,
			//    flex: 1,
			    padding: 10,
			    layout: 'hbox',
			    defaultType: 'textfield',
			    items: [{
							xtype: 'container',
							flex: 1,
							layout: 'anchor',
							defaultType: 'displayfield',
							items: [    
							    {
								        fieldLabel: 'Nombre',
								        padding: 15,
								        labelWidth: 70,
								        anchor:'90%',
								        name: 'persona'
							    }]
			    		},{
				    		xtype: 'container',
			                flex: 1,
			                layout: 'anchor',
			                defaultType: 'displayfield',
			                items: [
				                {
								        fieldLabel: 'Tipo de Socio',
								        padding: 15,
								        labelWidth: 120,
								        anchor:'90%',
								        name: 'roles'
							    }]
			    		}]
			    }]
			});
			
			// function editarwindow (id_edit, nombre_edit, monto_edit, cert_impr_edit, cert_ent_edit, cert_fecha_edit) {
				
	  //           var form = Ext.widget('form', {
	  //               layout: {
	  //                   type: 'vbox',
	  //                   align: 'stretch'
	  //               },
	  //               border: false,
	  //               bodyPadding: 10,
	
	  //               fieldDefaults: {
	  //                   labelAlign: 'left',
	  //                   labelWidth: 100,
	  //                   labelStyle: 'font-weight:bold'
	  //               },
	  //               items: [
	  //                      	{
			//                     xtype: 'displayfield',
			//                     fieldLabel: 'Nombre',	                    
			//                     labelWidth: 120,
			//                     value: nombre_edit,  
	  //               		},{
			//                     fieldLabel: 'Monto Pagado',   			                    
			//                     xtype: 'numberfield',
			// 			    	minValue: 0,
			// 			    	labelWidth: 120,
			// 			    	width: 250,
			// 			    	tabIndex: 2,
			// 			    	hideTrigger: true,
			// 			    	//anchor:'90%',
			// 			    	name: 'monto', 
			//                     value: monto_edit  
	  //               		},{
	  //               			xtype: 'fieldcontainer',
	  //                           fieldLabel: 'Certificado',
	  //                           labelWidth: 120,
	  //                           defaultType: 'checkboxfield',
	  //                           items: [
	  //                               {
	  //                                   boxLabel  : 'Se imprimio',
	  //                                   name      : 'imprimio',
	  //                                   inputValue: '1',
	  //                                   value: cert_impr_edit, 
	  //                                   uncheckedValue : 'N',
	  //                                   id        : 'imprimio'
	  //                               }, {
	  //                                   boxLabel  : 'Se entrego',
	  //                                   name      : 'entrego',
	  //                                   inputValue: '1',
	  //                                   value: cert_ent_edit,
	  //                                   uncheckedValue : 'N',
	  //                                   id        : 'entrego',
   //                                  	handler: function (checkbox, checked) {
   //                                           if (checked) {
   //                                          	 Ext.getCmp('fecha').show();
   //                                           }
   //                                           else if (!checked) {
   //                                          	 Ext.getCmp('fecha').hide();
   //                                           }
   //                                       }
	  //                               }
	  //                           ]	
	  //               		},{
   //                              fieldLabel: 'Fecha Entrega',
			// 		 	        xtype: 'datefield',
			// 		 	        hidden: true,
			// 		 	       	format: 'd/m/Y',
   //                              tabIndex: 4,
			// 		 	        labelWidth: 120,
			// 		 	        name: 'fecha',
			// 		 	        id: 'fecha'
	  //               		}
	  //               ],
	
	  //               buttons: [{
	  //                   text: 'Guardar',
	  //                   handler: function(b,e) {
	  //                   	var basicForm = b.up('form').getForm();  						
			// 	            var valoresForm = basicForm.getFieldValues();
		
			// 				Ext.Ajax.request({
			// 					   url: baseURL + '/actividad/actividad/editar-participante',
			// 					   success: function(response, opt){
			// 						   Ext.Msg.show({
			// 							    title:'Aviso',
			// 								msg:'Participante Modificado Correctamente',
			// 								closable: false,
			// 								width: 250
			// 						   });
			// 						   function hide_message() {
			// 						       Ext.defer(function() {
			// 						           Ext.MessageBox.hide();
			// 						       }, delay);
			// 						   }
			// 						   hide_message();
			// 						   //Ext.getCmp('filtros2').up('form').getForm().reset();
			// 						   participantesStore.load();
			// 					   },
			// 					   jsonData:{
			// 					       'put':{
			// 					    	   'act_actividad_participantes_id': id_edit,
			// 					    	   'monto_participante': valoresForm.monto,
			// 					    	   'se_imprimio_certificado': (valoresForm.imprimio) ? 'S' : 'N',
			// 					    	   'se_entrego_certificado': (valoresForm.entrego) ? 'S' : 'N',
			// 					    	   'fecha_entrega_certificado': (formatearFecha(valoresForm.fecha, 1))
										   
			// 					       }
			// 					   }
			// 				 });
			// 				 this.up('window').destroy();
	  //                   }
	  //               },{
	  //                   text: 'Cancelar',
	  //                   handler: function() {
	  //                       this.up('form').getForm().reset();
	  //                       this.up('window').close();
	  //                   }
	  //               }]
	                
	  //           });
	            
   //              if (cert_impr_edit == 'S')
			// 	{
			// 		Ext.getCmp('imprimio').setValue(true);
			// 	}					 
			// 	if (cert_ent_edit == 'S')
			// 	{
			// 		Ext.getCmp('entrego').setValue(true);
			// 	}
				
	  //           win = Ext.widget('window', {
	  //               title: 'Editar Participante',
	  //               closeAction: 'hide',
	  //               width: 400,
	  //               height: 260,
	  //               layout: 'fit',
	  //               resizable: true,
	  //               modal: true,
	  //               items: form
	  //           }); 
	  //      	 win.show();
	  //   	}
			
			// var agregarParticipante = Ext.create('Ext.form.Panel', {
			// 	 type:  'hbox',
			// 	 padding: '10 10 10 10',
			// 	 collapsible: true,
			// 	 name: 'agregarParticipante',
			// 	 title:'Agregar Participantes',
			// 	    width: 'fit',	
			// 	    height: 'fit',			           
			// 	    items:[
			// 			{
			// 			    xtype: 'container',
			// 			    id: 'filtros2',
			// 			    height: 45,
			// 			    layout:'hbox',
			// 			    items:[{   	
			// 					    	fieldLabel: 'Nombre',
			// 					    	xtype: 'combobox',
			// 					    	forceSelection: true,
			// 					        labelWidth: 90,
			// 					        store: posiblesParticipantesStore,
			// 					        displayField: 'mostrar',
			// 					        valueField: 'org_parte_id',
			// 					        width: 300,
			// 					        tabIndex: 1,
			// 					        padding: '10 0 5 15',
			// 				 	        anchor:'90%',
			// 					    	name: 'auxparticipante',
			// 					    	queryMode: 'remote',							        
			// 					        typeAhead: true,								        
			// 					        loadingText: 'Buscando...',
			// 					        hideTrigger: true,
			// 					        queryParam: 's[parte]',
			// 					        minChars: 1,          
			// 			    	  },{
			// 			    		  	fieldLabel: 'Monto Pagado',
			// 					    	labelWidth: 110,
			// 					    	xtype: 'numberfield',
			// 					    	minValue: 0,
			// 					    	width: 300,
			// 					    	tabIndex: 2,
			// 					    	hideTrigger: true,
			// 					    	anchor:'90%',
			// 					    	padding: '10 0 5 15',
			// 					    	name: 'monto', 
			// 			    	  },{ 
			//                              xtype: 'tbfill' 
			//                       },{					
			// 			           		xtype: 'button',
			// 			           		width: 100,
			// 			           		margin: '10 20 0 20',
			// 			            	text: 'Agregar',
			// 				            scale   : 'small',
			// 				            handler: function(b,e) {
							            	
			// 						           var basicForm = b.up('form').getForm();						
			// 						           var valoresForm = basicForm.getFieldValues();
		
			// 									var nuevoParticipante = valoresForm.auxparticipante;
			// 									var monto = valoresForm.monto;
			// 									var moneda = Ext.getCmp('cont_moneda_id').getValue();
												
			// 									Ext.Ajax.request({
			//  	        							   url: baseURL + '/actividad/actividad/set-participante',
			//  	        							   success: function(response, opt){
			//  	        								  Ext.getCmp('filtros2').up('form').getForm().reset();
			// 								                participantesStore.load();
			// 								                posiblesFormadoresStore.load();
			// 		        								posiblesParticipantesStore.load();
			//  	        								   Ext.Msg.show({
			//  	        									    title:'Aviso',
			//  	        										msg:'Participante Asignado a la Actividad',
			//  	        										closable: false,
			//  	        										width: 250
			//  	        								   });
			//  	        								   function hide_message() {
			//  	        								       Ext.defer(function() {
			//  	        								           Ext.MessageBox.hide();
			//  	        								       }, delay);
			//  	        								   }
			//  	        								  hide_message();
			//  	        							   },
			//  	        							   jsonData:{
			//  	        								   'post':{		 	        							       
			//  	        							    	    'act_actividad_id': aux,
			//  													'org_parte_id': nuevoParticipante,
			//  													'monto_participante': monto,
			//  													'cont_moneda_id': moneda
			//  	        								   }			 	        							       
			//  	        							   }
			//  	        						 });
			// 					            }  									        
			// 						}
			// 				   ]
			// 				}
			// 		  ]
			// });
			
			var gridAportes = Ext.create('Ext.grid.Panel', {
	            width: 'fit',
	            padding: '10 10 0 10',
	            height: 335,
	            title: 'Aportes',
	            region: 'center',              
	            layout: 'fit',
	            emptyText: "No existen aportes registrados para esta persona",        
	            store: aportesStore,
	            loadMask: true,
	            // grid columns
	            columns:[{
			                text: "Fecha",
			                dataIndex: 'fecha',
			                align: 'left',
			                flex: 0.5,
			                renderer: function(val, metadata, record, rowIndex, colIndex){ 
                				return  formatearFecha(val, 2);
                			}
		            	},{
			                text: "Monto",
			                dataIndex: 'monto_moneda',
			                align: 'center',
			                flex: 1
			            },{
			                text: "Tipo de Aporte",
			                dataIndex: 'tipo',
			                align: 'center',
			                flex: 1,
		            	},{
			                text: "Rol",
			                dataIndex: 'rol_socio',
			                align: 'center',
			                flex: 1,
		            	},{
			                xtype:'actioncolumn',
			                width:35,
			                align: 'center',
			                items: [{
			                    icon: baseURL+'/img/icons/grid/edit.png',  
			                    //tooltip: 'Edit',
			      //           handler: function(grid, rowIndex, colIndex) {
			      //               	var id_edit = participantesStore.getAt(rowIndex).get('act_actividad_participantes_id');
			      //               	var nombre_edit = participantesStore.getAt(rowIndex).get('mostrar');
			      //               	var monto_edit = participantesStore.getAt(rowIndex).get('monto_participante');
			      //               	var cert_impr_edit = participantesStore.getAt(rowIndex).get('se_imprimio_certificado');
			      //               	var cert_ent_edit = participantesStore.getAt(rowIndex).get('se_entrego_certificado');
			      //               	var cert_fecha_edit = participantesStore.getAt(rowIndex).get('fecha_entrega_certificado');
									// editarwindow(id_edit, nombre_edit, monto_edit, cert_impr_edit, cert_ent_edit, cert_fecha_edit);                        
			      //               }
			                }]
			            },{
			                xtype:'actioncolumn',
			                width: 35,
			                align: 'center',
			                items: [{
			                	icon: baseURL+'/img/icons/grid/delete.png',  
			                    //tooltip: 'Delete',
			            //         handler: function(grid, rowIndex, colIndex) {
			            //         	var id_delete = participantesStore.getAt(rowIndex).get('act_actividad_participantes_id');
			            //         	var nombre_delete = participantesStore.getAt(rowIndex).get('nombre');
			            //         	var apellido_delete = participantesStore.getAt(rowIndex).get('apellido');
			            //         	var auxmensaje = 'Confirma que desea eliminar al participante '+nombre_delete+' '+apellido_delete+' de esta actividad?';
			            //         	Ext.Msg.show({
			            //                 title:'Consulta',
			            //                 msg: auxmensaje,
			            //                 width: 250,
			            //                 buttons: Ext.Msg.YESNO,
			            //                 icon: Ext.Msg.QUESTION,
			            //                 fn: function(rec) {
			            //                    if (rec === "yes") {
			            //                 	   Ext.Ajax.request({
			        				// 			   url: baseURL + '/actividad/actividad/desasociar-participante',
			        				// 			   success: function(response, opt){
			        				// 				   Ext.Msg.show({
			        				// 					    title:'Aviso',
			        				// 						msg:'Participante eliminado de la Actividad',
			        				// 						closable: false,
			        				// 						width: 250
			        				// 				   });
			        				// 				   function hide_message() {
			        				// 				       Ext.defer(function() {
			        				// 				           Ext.MessageBox.hide();
			        				// 				       }, delay);
			        				// 				   }
			        				// 				   hide_message();
			        				// 				   Ext.getCmp('filtros2').up('form').getForm().reset();
			        				// 				   id_delete = null;
			        				// 				   participantesStore.load();
			        				// 				   posiblesFormadoresStore.load();
			        				// 				   posiblesParticipantesStore.load();
			        				// 			   },
			        				// 			   jsonData:{
															// 'participante': id_delete,
			        				// 			   }
			        				// 		 });
			            //                   }
			            //                    else{
			            //                 	   this.close();
			            //                    }	                               
			            //                }
			            //            }); 
			            //         }
		                }]
	            }       
	            ]
	            	        	
			 });
			 			
			var pantalla = Ext.create('Ext.form.Panel', {
		    width: 'fit',
		    height: 530,
		    	items:[
				         {	
				        	 xtype: 'panel',
							 items: [pantallaActividad]
					        
				         },{
				        	 xtype: 'container',
							 items:[gridAportes],
				         }
				],
				  listeners:{
							'render':function(){
									Ext.getCmp('topTabPanel').setActiveTab(4);
	//								Ext.getCmp('actividadTabPanel').setActiveTab(0);
							}
				  }	    	
			});
                        
		cargarDatos();
		Ext.getCmp('centerPanel').add(pantalla);
});

			
		</script>
    </head>
    <body>
    </body>
</html>
