<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		var cargarDatos = function (){
			aux = buscarId();
			Ext.Ajax.request({
			    url: baseURL +'/actividad/actividad/get',
			    params: {
			        'id': aux,
			    },
			    success: function(response) {
			    	var campos = Ext.decode(response.responseText);
			    	var form = Ext.getCmp('form').getForm();
			    	
			    	for (campo in campos) {
				    	if (campo == "documentos"){
							var doc = (campos[campo]);
							console.log(doc["org_documento_id"]);
			    		}	
				    	var name = form.findField(campo);
				    		if (name) {
				    			if (campo == "fecha_inicio" || campo == "fecha_fin")
						    	{
				    				if (campos[campo]){
							    		var fecha = campos[campo];
					 			    	var fecha2 = fecha.split("-");
					 			    	var result = fecha2[2]+'-'+fecha2[1]+'-'+fecha2[0];
					 			    	campos[campo] = result;
					 			    	name.setValue(campos[campo]);
				    				}
						    	 }else if (campo == "asistencia" || campo == "atelier")
							    	{
								    	if (campos[campo] == 'S'){
								    		campos[campo] = 'Si';
								    	}
								    	else if (campos[campo] == 'N'){
								    		campos[campo] = 'No';
								    	}
					 			    	name.setValue(campos[campo]);
								 	} else{
								    
									    	name.setValue(campos[campo]);
									    	console.log(campo);
							     }
					    }	}	
			    	}
				});
		};

		var pantallaActividad = Ext.create('Ext.form.Panel', {
			id: 'form',
			items:[{
			    xtype: 'panel',
			    bodyStyle: {
		        	background: '#C8CED8',
		        },
			    title: 'Datos de la Actividad',
			    height: 'fit',
			    width: 'fit',
			    border: 1,
			    padding: 10,
			    layout: 'hbox',
			    defaultType: 'textfield',
			    items: [{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'displayfield',
					items: [    
					    {
						        fieldLabel: 'Nombre',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'nombre_identificador',
						},{
						        fieldLabel: 'Costo',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
					 	        name: 'monto',
			    	 	},{
						        fieldLabel: 'Estado',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
					 	        name: 'estado', 
			    	    },{
						    	fieldLabel: 'Inicio',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						    	name: 'fecha_inicio',
				   	 	}
			    	]},{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'displayfield',
					items: [{
				    	        fieldLabel: 'Tipo de Act.',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'actividad_tipo'
				    	 },{
					        	fieldLabel: 'Moneda',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
					 	        name: 'moneda'
					     },{
						        fieldLabel: 'Tipo',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
					 	        name: 'tipo', 
			    	     },{
						    	fieldLabel: 'Fin',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						    	name: 'fecha_fin',
					   	  }
			    	]},{
			    		xtype: 'container',
		                flex: 1,
		                layout: 'anchor',
		                defaultType: 'displayfield',
		                items: [{
					    		 	fieldLabel: 'Duraci&oacute;n (hs)',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'duracion',
							  },{
							    	fieldLabel: 'Participantes',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'nro_personas',	  
					    	  },{
							    	fieldLabel: 'A&ntilde;o',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'anho_formacion',	  
					    	  },{
							    	fieldLabel: "Observaci&oacute;n",
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							    	name: 'observaciones',
							  }
			    		]
			    	}]},{
		    	xtype: 'container',
		 	    height: 200,
		 	    width: 'fit',
		 	   layout: 'hbox',
		 	   // flex: 1,
		 	   // padding: '5 0 10 440',
		 	    items:[
				  { xtype: 'tbfill' },
		 	      {	  
		 	    	  xtype: 'button',
		 	    	  margin: '5 0 15 0',
				      scale: 'large',
				      width: 100,
				      text: 'Editar',
				      handler: function() {
	                   		var url = baseURL+'/actividad/actividad/editar-ui#?id='+aux;  
	                   		window.location = url;     
				      }
		 	      },{
		 	    	  xtype: 'button',
		 	    	  margin: '5 15 15 20',
				      scale: 'large',
				      width: 100,
				      text: 'Volver',
					  //disabled: true,
					  handler: function() {
						  window.location = baseURL+'/actividad/actividad/index-ui';
					}
		 	      }
			    ]
		     }],
			});
		
		var pantalla = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 
			 width: 'fit',
			 height: 'fit',		           
			 items:[
								{
									xtype: 'tabpanel',
									//style:'background-color: #C8CED8',
									//layout: 'fit',
									items: [{
								        title: 'Datos de Actividad',
								        tabConfig: {style:'width:240px'},
								        items:[pantallaActividad],
								    },{
								        title: 'Formadores',
								        tabConfig: {style:'width:240px'},
								        items: []
								    },{
								        title: 'Participantes',
								        tabConfig: {style:'width:240px'},
								        items: []								       
								    }]
								}
								
			  ],
			  listeners:{
						'render':function(){
								Ext.getCmp('topTabPanel').setActiveTab(1);
//								Ext.getCmp('actividadTabPanel').setActiveTab(1);
						}
			  }	    	
		});

		cargarDatos();
		Ext.getCmp('centerPanel').add(pantalla);
});

			
		</script>
    </head>
    <body>
    </body>
</html>
