<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

				Ext.define('formadores', {
					extend: 'Ext.data.Model',
					fields: [
						{
							type: 'int',
							name: 'act_actividad_formadores_id'
						},{
							type: 'int',
							name: 'act_actividad_id'
						},{
							type: 'int',
							name: 'org_parte_rol_id'
						},{
							type: 'string',
							name: 'nombre'
						},{
							type: 'string',
							name: 'apellido'
						}
					]
				});
				
				Ext.define('participantes', {
					extend: 'Ext.data.Model',
					fields: [
						{
							type: 'int',
							name: 'act_actividad_participantes_id'
						},{
							type: 'int',
							name: 'act_actividad_id'
						},{
							type: 'int',
							name: 'org_parte_rol_id'
						},{
							type: 'string',
							name: 'nombre'
						},{
							type: 'string',
							name: 'apellido'
						}
					]
				});

		var cargarDatos = function (){
			aux = buscarId();
			Ext.Ajax.request({
			    url: baseURL +'/actividad/actividad/get',
			    params: {
			        'id': aux,
			    },
			    success: function(response) {
			    	formadoresStore.load({
				        params: {
				            "s[actividad]":aux,
				            'p[limit]':'all'	
					}});
				    participantesStore.load({
						params: {
						    "s[actividad]":aux,
						    'p[limit]':'all'	
				    }});
	                
			    	var campos = Ext.decode(response.responseText);
			    	var form = Ext.getCmp('form').getForm();
			    	
			    	for (campo in campos) {
				    	if (campo == "documentos"){
							var doc = (campos[campo]);
							console.log(doc["org_documento_id"]);
			    		}	
				    	var name = form.findField(campo);
				    		if (name) {
				    			if (campo == "fecha_inicio" || campo == "fecha_fin")
						    	{
				    				if (campos[campo]){
							    		var fecha = campos[campo];
					 			    	var fecha2 = fecha.split("-");
					 			    	var result = fecha2[2]+'-'+fecha2[1]+'-'+fecha2[0];
					 			    	campos[campo] = result;
					 			    	name.setValue(campos[campo]);
				    				}
						    	 }else if (campo == "asistencia" || campo == "atelier")
							    	{
								    	if (campos[campo] == 'S'){
								    		campos[campo] = 'Si';
								    	}
								    	else if (campos[campo] == 'N'){
								    		campos[campo] = 'No';
								    	}
					 			    	name.setValue(campos[campo]);
								 	} else if (campo == "duracion")
							    	{
								 		if (campos["modalidad_act"] == 'D'){
								    		campos[campo] = campos[campo] + ' d&iacute;as';
								    	}
								    	else if (campos["modalidad_act"] == 'H'){
								    		campos[campo] = campos[campo] + ' horas';
								    	}
									    	name.setValue(campos[campo]);
								 	} else{ 								    
									    	name.setValue(campos[campo]);
							     }
					    }	}	
			    	}
				});
		};

		var formadoresStore = Ext.create('Ext.data.Store', {
			model: 'formadores',
			proxy: {
				type: 'ajax',
				extraParams: {'s[actividad]':aux, 'p[limit]':'all'},
				headers: {'Accept':'application/json'},
				url: baseURL + '/actividad/actividad/formadores',
				reader: {
					type: 'json',
					root: 'records'
				}
			},
			autoLoad: false
		});

		var participantesStore = Ext.create('Ext.data.Store', {
			model: 'participantes',
			proxy: {
				type: 'ajax',
				extraParams: {'s[actividad]':aux, 'p[limit]':'all'},
				headers: {'Accept':'application/json'},
				url: baseURL + '/actividad/actividad/participantes',
				reader: {
					type: 'json',
					root: 'records'
				}
			},
			autoLoad: false
		});
		
		var pantallaActividad = Ext.create('Ext.form.Panel', {
			id: 'form',
			items:[{
			    xtype: 'panel',
			    bodyStyle: {
		        	background: '#C8CED8',
		        },
			    title: 'Datos de la Actividad',
			    height: 380,
			    width: 'fit',
			    border: 1,
			    padding: 10,
			    layout: 'hbox',
			    defaultType: 'textfield',
			    items: [{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'displayfield',
					items: [    
					    {
						        fieldLabel: 'Nombre',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'titulo',
						},{
				    		 	fieldLabel: 'Ciclo',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'ciclo',
						},{
						    	fieldLabel: 'Inicio',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						    	name: 'fecha_inicio',
				   	 	},{
						    	fieldLabel: 'Fin',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						    	name: 'fecha_fin',
					   	},{
						    	fieldLabel: "Observaci&oacute;n",
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						    	name: 'observaciones',
					 	 }
			    	]},{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'displayfield',
					items: [{
				    	        fieldLabel: 'Tipo de Actividad',
						        padding: 15,
						        labelWidth: 140,
						        anchor:'90%',
						        name: 'actividad_tipo'
				    	 },{
						        fieldLabel: 'Costo Referencial',
						        padding: 15,
						        labelWidth: 140,
						        anchor:'90%',
					 	        name: 'precio',
			    	 	 },{
						    	fieldLabel: 'A&ntilde;o de Formaci&oacute;n',
						        padding: 15,
						        labelWidth: 140,
						        anchor:'90%',
						        name: 'anho_formacion',	  
				    	 },{
						        fieldLabel: 'Atelier',
						        padding: 15,
						        labelWidth: 140,
						        anchor:'90%',
						        name: 'atelier',
						},
			    	]},{
			    		xtype: 'container',
		                flex: 1,
		                layout: 'anchor',
		                defaultType: 'displayfield',
		                items: [{
					    		 	fieldLabel: 'Formador',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'formador',
							  },{
					    		 	fieldLabel: 'Recaudaci&oacute;n',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'recaudacion',
							  },{
					    		 	fieldLabel: 'Duraci&oacute;n',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'duracion',
							  },{
							    	fieldLabel: 'Participantes',
							        padding: 15,
							        labelWidth: 110,
							        anchor:'90%',
							        name: 'nro_personas',	  
					    	  }
			    		]
			    	}]}],
			});

// 		var gridFormadores = Ext.create('Ext.grid.Panel', {
//             width: 'fit',
//             padding: '10 10 0 10',
//             height: 380,
//             title: 'Formadores de la Actividad',
//             region: 'center',              
//             layout: 'fit',
//             emptyText: "No existen Formadores para esta actividad",        
//             store: formadoresStore,
//             loadMask: true,
//             // grid columns
//             columns:[{
// 		                text: "Nombre",
// 		                dataIndex: 'nombre',
// 		                align: 'left',
// 		                width: 180,
// 	            	},{
// 		                text: "Apellido",
// 		                dataIndex: 'apellido',
// 		                align: 'left',
// 		                flex: 1,
// 		            }   
//             ]         	        	
// 		 });

		var gridParticipantes = Ext.create('Ext.grid.Panel', {
            width: 'fit',
            padding: '10 10 0 10',
            height: 380,
            title: 'Participantes de la Actividad',
            region: 'center',              
            layout: 'fit',
            emptyText: "No existen Participantes para esta actividad",        
            store: participantesStore,
            loadMask: true,
            // grid columns
            columns:[{
		                text: "Nombre",
		                dataIndex: 'nombre',
		                align: 'left',
		                width: 180,
	            	},{
		                text: "Apellido",
		                dataIndex: 'apellido',
		                align: 'left',
		                flex: 1,
		            }
            ]         	        	
		 });
	
		var pantalla = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 
			 width: 'fit',
			 height: 'fit',		           
			 items:[
								{
									xtype: 'tabpanel',
									tabPosition: 'left',
									height: 390,
								    width: 'fit',
									//style:'background-color: #C8CED8',
									//layout: 'fit',
									items: [{
								        title: 'Datos de Actividad',
								        //tabConfig: {style:'width:240px'},
								        items:[pantallaActividad],
								    //},{
								      //  title: 'Formadores',
								        //tabConfig: {style:'width:240px'},
								       // items: [gridFormadores]
								    },{
								        title: 'Participantes',
								        //tabConfig: {style:'width:240px'},
								        items: [gridParticipantes]								       
								    }]
								},{
							    	xtype: 'container',
							 	    height: 200,
							 	    width: 'fit',
							 	   layout: 'hbox',
							 	   // flex: 1,
							 	   // padding: '5 0 10 440',
							 	    items:[
									  { xtype: 'tbfill' },
							 	      {	  
							 	    	  xtype: 'button',
							 	    	  margin: '5 0 15 0',
									      scale: 'large',
									      width: 100,
									      text: 'Editar',
									      handler: function() {
						                   		var url = baseURL+'/actividad/actividad/editar-ui#?id='+aux;  
						                   		window.location = url;     
									      }
							 	      },{
							 	    	  xtype: 'button',
							 	    	  margin: '5 15 15 20',
									      scale: 'large',
									      width: 100,
									      text: 'Volver',
										  //disabled: true,
										  handler: function() {
											  window.location = baseURL+'/actividad/actividad/index-ui';
										}
							 	      }
								    ]
							     }
								
			  ],
			  listeners:{
						'render':function(){
								Ext.getCmp('topTabPanel').setActiveTab(1);
//								Ext.getCmp('actividadTabPanel').setActiveTab(1);
						}
			  }	    	
		});

		cargarDatos();
		Ext.getCmp('centerPanel').add(pantalla);
});

			
		</script>
    </head>
    <body>
    </body>
</html>
