<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxnombre = null;
			var auxcodigo = null;
			var auxnivel = null;
			var auxmodalidad = null;
			var auxcriterio = null;
	
			var itemsPorPagina = 10
			var page = 0;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('actividad', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_actividad_id'
				},{
					type: 'string',
					name: 'fecha_inicio'
				},{
					type: 'string',
					name: 'fecha_fin'
				},{
					type: 'string',
					name: 'nombre_identificador'
				},{
					type: 'float',
					name: 'duracion'
				},{
					type: 'string',
					name: 'estado'
				},{
					type: 'float',
					name: 'monto'
				},{
					type: 'string',
					name: 'observaciones'
				},{
					type: 'string',
					name: 'tipo'
				},{
					type: 'int',
					name: 'nro_personas'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'actividad_tipo'
				},{
					type: 'int',
					name: 'anho'
				},{
					type: 'string',
					name: 'moneda'
				},
			]
		});

		Ext.define('nivel', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_nivel_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'descripcion'
				}
			]
		});

		Ext.define('modalidad', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_modalidad_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'descripcion'
				}
			]
		});

		Ext.define('criterio', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_criterio_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'codigo'
				},{
					type: 'float',
					name: 'horas'
				},{
					type: 'date',
					name: 'fecha_alta'
				},{
					type: 'date',
					name: 'fecha_baja'
				}
			]
		});

		var nivelStore = Ext.create('Ext.data.Store', {
			model: 'nivel',
			proxy: {
				type: 'ajax',
				extraParams: {'p[limit]':'all'},
				headers: {'Accept':'application/json'},
				url: baseURL + '/actividad/combos/act-nivel?format=json',
				reader: {
					type: 'json',
					root: 'records'
				}
			},
			autoLoad: true
		});

		var modalidadStore = Ext.create('Ext.data.Store', {
			model: 'modalidad',
			proxy: {
				type: 'ajax',
				extraParams: {'p[limit]':'all'},
				headers: {'Accept':'application/json'},
				url: baseURL + '/actividad/combos/act-modalidad?format=json',
				reader: {
					type: 'json',
					root: 'records'
				}
			},
			autoLoad: true
		});

		var criterioStore = Ext.create('Ext.data.Store', {
			model: 'criterio',
			proxy: {
				type: 'ajax',
				extraParams: {'p[limit]':'all'},
				headers: {'Accept':'application/json'},
				url: baseURL + '/actividad/combos/act-criterio?format=json',
				reader: {
					type: 'json',
					root: 'records'
				}
			},
			autoLoad: true
		});
		
		var actividadStore = Ext.create('Ext.data.Store', {
			model: 'actividad',
			pageSize: itemsPorPagina, 
			proxy: {
				type: 'ajax',
				  extraParams:{
				    	"p[limit]": itemsPorPagina,
						"p[page]":  page, 
				  },
				headers: {'Accept':'application/json'},
				url: baseURL + '/actividad/actividad/index?format=json',
				reader: {
					type: 'json',
					root: 'records',
					totalProperty: 'numResults'
				}
			},
			autoLoad: true
		});


		var comboNivel = Ext.create('Ext.form.field.ComboBox', {
			fieldLabel: 'Nivel',
	        xtype: 'combobox',
	        labelWidth: 50,
	        width: 180,
	        store: nivelStore,
	        displayField: 'nombre',
	        queryMode: 'local',
	        valueField: 'act_nivel_id',
	        padding: '5 10 5 0',
 	        anchor:'90%',
 	        name: 'nivel',
	  	});

		var comboModalidad = Ext.create('Ext.form.field.ComboBox', {
			fieldLabel: 'Modalidad',
	        xtype: 'combobox',
	        labelWidth: 80,
	        width: 200,
	        store: modalidadStore,
	        displayField: 'nombre',
	        queryMode: 'local',
	        valueField: 'act_modalidad_id',
	        padding: '5 10 5 0',
 	        anchor:'90%',
 	        name: 'modalidad',
	  	});

		var comboCriterio = Ext.create('Ext.form.field.ComboBox', {
			fieldLabel: 'Criterio',
	        xtype: 'combobox',
	        labelWidth: 70,
	        width: 280,
	        store: criterioStore,
	        displayField: 'nombre',
	        queryMode: 'local',
	        valueField: 'act_criterio_id',
	        padding: '5 10 5 0',
 	        anchor:'90%',
 	        name: 'criterio',
	  	});
		  
		var panelFiltros = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 collapsible: true,
			 title:'Filtros de B&uacute;squeda',
			    width: 'fit',	
			    height: 'fit',			           
			    items:[
				{
				    xtype: 'container',
				    id: 'filtros',
				    height: 40,
				    layout:'hbox',
				    items:[{   	
					    		xtype: 'textfield',
						        fieldLabel: 'Nombre',
						        padding: '10 0 5 15',
						        labelWidth: 70,
						        width: 250,
						        anchor:'90%',
						        name: 'nombre',
							    flex: 0.5    
				    	  },{   	
					    		xtype: 'textfield',
						        fieldLabel: 'C&oacute;digo',
						        padding: '10 0 5 20',
						        labelWidth: 60,
						        width: 180,
						        anchor:'90%',
						        name: 'codigo',
							    flex: 0.4    
				    	  },{
							    xtype: 'container',
							    padding: '5 0 0 20', //margen del Form 'arriba lateral abajo'
							    flex: 0.5,
							    items: [comboNivel]
						   }, 
				    	   {
						        xtype: 'container',
						        padding: '5 0 0 0', 
						        flex: 0.5,
						        items: [comboModalidad]
					    	},
					    	{
						        xtype: 'container',
						        padding: '5 0 0 0', 
						        flex: 0.65,
						        items: [comboCriterio]
					    	}
					   ]
					},{
						xtype: 'container',
					    height: 45,
					    layout:'hbox',
					    items:[{
			
				           		xtype: 'button',
				           		width: 100,
				           		margin: '10 0 0 20',
				            	text: 'Filtrar',
					            scale   : 'medium',
					            handler: function(b,e) {
					            	
							           var basicForm = b.up('form').getForm();						
							           var valoresForm = basicForm.getFieldValues();

					           		    var auxnombre = valoresForm.nombre;
					           		    var auxcodigo = valoresForm.codigo;
					           			
							           	auxnivel = valoresForm.nivel;
							           	auxmodalidad = valoresForm.modalidad;
							           	auxcriterio = valoresForm.criterio;
			
										//inicializo los pages
							           	page = 0;
										gridActividad.store.currentPage = 1;
										
						                actividadStore.load({
											params: {
												"s[nombre]": auxnombre,
												"s[codigo]": auxcodigo,
												"s[nivel]": auxnivel,
												"s[modalidad]": auxmodalidad,
												"s[criterio]": auxcriterio
									   		} 
						               });
						            }//end of handler  
									        
								},{
			
								  		xtype: 'button',
								  		width: 100,
								  		margin: '10 0 0 15',
					               		text: 'Limpiar',
						           		scale   : 'medium',
						           		handler: function(b,e) {
						           			//inicializo los pages
								           	page = 0;
											gridActividad.store.currentPage = 1;
											//console.log(this);
						           			b.up('form').getForm().reset();
						           			actividadTipoStore.load();						   	
				           		  		}
								}]}
				    	]
		});
    	
		var gridActividad = Ext.create('Ext.grid.Panel', {
            //title: 'Profesi&oacute;n',
            selModel: {
                checkOnly: true,
                injectCheckbox: 1
            },
            width: 'fit',
            padding: '5 0 0 0',
            height: 385,
            region: 'center',  
	           dockedItems: [
	                {     
		          	     xtype: 'toolbar',
                         dock: 'top',
                         items: [
                         { 
                             xtype: 'tbfill' 
                         },{
     			            xtype: 'button',	
    			            text: 'Crear Actividad',
    			            handler: function() {
    			            	window.location = baseURL+'/actividad/actividad/crear-ui';
    						}
    		            }]
	                }
	                ,{
                    xtype: 'pagingtoolbar',
                    store: actividadStore, 
                    dock: 'bottom',
                    displayInfo: true,
                    listeners: {
                        'afterrender': function (component)
                        {
                            component.down('#refresh').hide()
                        },single: true
                    },
                    displayMsg: 'Registro {0} al {1} de {2}',
                    beforePageText: 'P&aacute;gina',
                    afterPageText : 'de {0}',
                    moveNext : function(){ 
                   		page = page + itemsPorPagina;
                   	 	this.store.currentPage++;
           				actividadStore.load({
	       				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
	       				    }
       					});
           					console.log("page store: ", page);
          				    console.log("page extjs: ",this.store.currentPage);	
                	 },
                 	 movePrevious : function(){ 
                 		page = page - itemsPorPagina;
						this.store.currentPage--;
						actividadStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,        
		   				    }
   						});
	       					console.log("page store: ", page);
	      				    console.log("page extjs: ",this.store.currentPage);	
            		 },
             		moveFirst : function(){ 
             			page = 0;
						this.store.currentPage = 1;
						actividadStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);	
            	 	},
            	 	moveLast : function(){                 	 	
            	 		if (this.getStore().getTotalCount() % itemsPorPagina == "0"){
	                	 	page = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)-1)*itemsPorPagina;
	                	 	this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina));
            	 		}
						else
						{
							page = parseInt(this.getStore().getTotalCount() / itemsPorPagina)*itemsPorPagina;
							this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)+1);
						}
            	 		actividadStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);         					
            	 	},
                }
	                ],                       
            layout: 'fit',
            emptyText: "No existen tipo de actividades cargadas",
            
            store: actividadStore,
            loadMask: true,
            // grid columns
            columns:[{
                text: "Actividad",
                dataIndex: 'nombre_identificador',
                align: 'left',
                flex: 1,
                renderer: function(val, metadata, record, otraCosa, otraCosaMas) {
                    console.log(metadata);
                    return '<a href="'+baseURL+'/actividad/actividad/get-ui#?id=' + metadata.record.data.act_actividad_id +'">'+ val +'</a>';
            	}
            },{
                text: "Tipo de Act.",
                dataIndex: 'actividad_tipo',
                align: 'center',
                flex: 1,
            },{
                text: "Estado",
                dataIndex: 'estado',
                align: 'center',
                flex: 0.5,
            },{
                text: "Tipo",
                dataIndex: 'tipo',
                align: 'center',
                flex: 0.4,
            },{
                text: "Duraci&oacute;n (hs)",
                dataIndex: 'duracion',
                align: 'center',
                flex: 0.6,
            },{
                text: "Monto",
                dataIndex: 'monto',
                align: 'center',
                flex: 0.6,
            },{
                text: "Moneda",
                dataIndex: 'moneda',
                align: 'center',
                flex: 0.6,
            },{
                text: "Participantes",
                dataIndex: 'nro_personas',
                align: 'center',
                flex: 0.6,
            },{
                text: "Inicio",
                dataIndex: 'fecha_inicio',
                align: 'center',
                flex: 0.6,
            },{
                text: "Fin",
                dataIndex: 'fecha_fin',
                align: 'center',
                flex: 0.6,
            },{
                text: "Observaci&oacute;n",
                dataIndex: 'observaciones',
                align: 'center',
                flex: 1,
            },{
                xtype:'actioncolumn',
                width:35,
                align: 'center',
                items: [{
                    icon: baseURL+'/img/icons/grid/edit.png',  
                    tooltip: 'Edit',
               		handler: function(grid, rowIndex, colIndex) {
                   		var url = baseURL+'/actividad/actividad/editar-ui#?id='+actividadStore.getAt(rowIndex).get('act_actividad_id');  
                   		window.location = url;                     
                    }
                }]
            },{
                xtype:'actioncolumn',
                width: 35,
                align: 'center',
                items: [{
                	icon: baseURL+'/img/icons/grid/delete.png',  
                    //tooltip: 'Delete',
                    handler: function(grid, rowIndex, colIndex) {
                    	var id_delete = actividadStore.getAt(rowIndex).get('act_actividad_id');
                    	var nombre_delete = actividadStore.getAt(rowIndex).get('nombre_identificador');
                    	var auxmensaje = 'Confirma que desea borrar la Actividad '+nombre_delete+'?';
                    	Ext.Msg.show({
                            title:'Consulta',
                            msg: auxmensaje,
                            width: 250,
                            buttons: Ext.Msg.YESNO,
                            icon: Ext.Msg.QUESTION,
                            fn: function(rec) {
                               if (rec === "yes") {
                            	   Ext.Ajax.request({
        							   url: baseURL + '/actividad/actividad/delete',
        							   success: function(response, opt){
        								   Ext.Msg.show({
        									    title:'Aviso',
        										msg:'Actividad Borrada Correctamente'
        								   });
        								   function hide_message() {
        								       Ext.defer(function() {
        								           Ext.MessageBox.hide();
        								       }, delay);
        								   }
        								   hide_message();
        								   actividadStore.load();
        							   },
        							   jsonData:{
        							       'delete':{
												'act_actividad_id': id_delete,
        							       }
        							   }
        						 });
                              }
                               else{
                            	   this.close();
                               }	                               
                           }
                       });

                    	
                        
                    }
                }]
            }       
            ]
            	        	
		 });

		 
			
		var pantalla = Ext.create('Ext.panel.Panel', {
			//id: 'margen',
			padding: '5 0 0 10', 
		    //title: ' ',
		    width: 'fit',
		    height: 510,
		    items:[
// 		         {	
// 		        	 xtype: 'panel',
// 					 items: [panelFiltros]
			        
// 		         }
		         ,{
		        	 xtype: 'container',
					 items: [gridActividad]
		         }
		    ],
		    listeners:{
				'render':function(){
					Ext.getCmp('topTabPanel').setActiveTab(1);
					Ext.getCmp('actividadTabPanel').setActiveTab(0);
				}
			}
		});

			Ext.getCmp('centerPanel').add(pantalla);


				
});

			
		</script>
    </head>
    <body>
    </body>
</html>
