<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Tipo de Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux=null;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
						var si_no = Ext.create('Ext.data.Store', {
						    fields: ['id', 'nombre'],
						    data : [
							        {"id": "S", "nombre":"Si"},
							        {"id": "N", "nombre":"No"}
						        ]
						});
						
						var si_no2 = Ext.create('Ext.data.Store', {
						    fields: ['id', 'nombre'],
						    data : [
							        {"id": "S", "nombre":"Si"},
							        {"id": "N", "nombre":"No"}
						        ]
						});

						var si_no3 = Ext.create('Ext.data.Store', {
						    fields: ['id', 'nombre'],
						    data : [
							        {"id": "S", "nombre":"Si"},
							        {"id": "N", "nombre":"No"}
						        ]
						});

						var comboModalidad = Ext.create('Ext.data.Store', {
						    fields: ['id', 'nombre'],
						    data : [
							        {"id": "D", "nombre":"D&iacute;as de Formaci&oacute;n"},
							        {"id": "H", "nombre":"Horas de Formaci&oacute;n"}
						        ]
					});
					
					var buscarId = function(){
						if (window.location.hash) {
						    var params = (window.location.hash.substr(1)).split("#");
						        var id = params[0].split("=");
								return id[1];
						}
					};
			
					var cargarDatos = function (){
						aux = buscarId();
						Ext.Ajax.request({
						   	url: baseURL +'/actividad/actividad-tipo/get',
							    params: {
							        'id': aux,
							    },
					    success: function(response) {
					    	var campos = Ext.decode(response.responseText);
					    	var form = Ext.getCmp('form').getForm();
					    	
					    	for (campo in campos) {
						    	var name = form.findField(campo);
						    		if (name) {			    
											    name.setValue(campos[campo]);						    					
					    			}
					    	}
					    }
					});
				};

				var buttonEditar = function(b,e)
				{
								var basicForm = b.up('form').getForm();
					if(basicForm.isValid())
					{  						
					            var valoresForm = basicForm.getFieldValues();

								Ext.Ajax.request({
									   url: baseURL + '/actividad/actividad-tipo/put',
									   success: function(response, opt){
										   Ext.Msg.show({
											    title:'Aviso',
												msg:'Tipo de Actividad Editado Correctamente',
												closable: false,
												width: 250
										   });
										   function hide_message() {
										       Ext.defer(function() {
										           Ext.MessageBox.hide();
										       }, delay);
										   }
										   hide_message();
										   window.location = baseURL+'/actividad/actividad-tipo/index-ui';
									   },
// 									    failure: function(response, opt){
// 											   console.log(response);
// 												Ext.MessageBox.show({
// 						                            title: 'Error de Edici&oacute;n',
// 						                            msg: response.responseText,
// 						                            icon: Ext.MessageBox.ERROR,
// 						                            buttons: Ext.Msg.OK
// 						                        });
// 										},
										failure: function(response, opt){
											   var aux_mensaje = Ext.decode(response.responseText);
											   var mensaje = " ";
												   for (error in aux_mensaje.datos) {
					                            		mensaje = mensaje +"- "+ error +": "+aux_mensaje.datos[error]+'<br>';  
					                                }
												Ext.MessageBox.show({
						                            title: aux_mensaje.mensaje,
						                            msg: mensaje,
						                            icon: Ext.MessageBox.ERROR,
						                            buttons: Ext.Msg.OK
						                        });
										},
									   jsonData:{
									       'put':{
									    	   'act_actividad_tipo_id': aux,
											   'titulo': valoresForm.titulo,
											   'modalidad': valoresForm.modalidad,
											   'horas':  valoresForm.horas,
											   'activo':  valoresForm.activo,
											   'homologada':  valoresForm.homologada,	  
											   'relacion_ayuda':  valoresForm.relacion_ayuda,
											   'descripcion': valoresForm.descripcion,	  	  	   
									       }
									   }
								 });
					}
					else
					{
						Ext.Msg.alert('Aviso','Hay campos inv&aacute;lidos');
						return;
					}  	
					
				};
		var pantallaActividad = Ext.create('Ext.form.Panel', {
			id: 'form',
			items:[{
			    xtype: 'panel',
			    bodyStyle: {
		        	background: '#C8CED8',
		        },
			    title: 'Tipo de Actividad',
			    //collapsible: true,
			    //anchor:'90%',
			    height: 'fit',
			    width: 'fit',
			    border: 1,
			    padding: 10,
			    layout: 'hbox',
			    defaultType: 'textfield',
			    items: [{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'textfield',
					items: [    
					    {
						        fieldLabel: 'Nombre',
						        allowBlank: false,
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'titulo'
					    },{
						        fieldLabel: 'Activo',
						        xtype: 'combobox',
						        forceSelection: true,
						        labelWidth: 110,
						        store: si_no,
						        displayField: 'nombre',
						        queryMode: 'local',
						        valueField: 'id',
						        allowBlank: false,
						        padding: 15,
						        name: 'activo',
					 	        anchor:'90%',
						},{
						    	xtype: 'textarea',
						        fieldLabel: 'Descripci&oacute;n',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'descripcion',
						}
			    	]},{
			    		xtype: 'container',
		                flex: 1,
		                layout: 'anchor',
		                defaultType: 'textfield',
		                items: [{
					        fieldLabel: 'Modalidad',
					        xtype: 'combobox',
					        forceSelection: true,
					        labelWidth: 110,
					        store: comboModalidad,
					        displayField: 'nombre',
					        queryMode: 'local',
					        valueField: 'id',
					        allowBlank: false,
					        padding: 15,
				 	        anchor:'90%',
				 	        name: 'modalidad', 
			    	    },{
					        fieldLabel: 'Homologada',
					        xtype: 'combobox',
					        forceSelection: true,
					        labelWidth: 110,
					        store: si_no2,
					        displayField: 'nombre',
					        queryMode: 'local',
					        valueField: 'id',
					        allowBlank: false,
					        padding: 15,
				 	        anchor:'90%',
				 	        name: 'homologada',
						},{
					        fieldLabel: 'Es R.A.',
					        xtype: 'combobox',
					        forceSelection: true,
					        labelWidth: 110,
					        store: si_no3,
					        displayField: 'nombre',
					        queryMode: 'local',
					        valueField: 'id',
					        allowBlank: false,
					        padding: 15,
				 	        anchor:'90%',
				 	        name: 'relacion_ayuda',
						}]
			    	}]},{
		    	xtype: 'container',
		 	    height: 200,
		 	    width: 'fit',
		 	   layout: 'hbox',
		 	   // flex: 1,
		 	   // padding: '5 0 10 440',
		 	    items:[
				  { xtype: 'tbfill' },
		 	      {	  
		 	    	  xtype: 'button',
		 	    	  margin: '5 0 15 0',
				      scale: 'large',
				      width: 100,
				      text: 'Guardar',
				      handler: buttonEditar
		 	      },{
		 	    	  xtype: 'button',
		 	    	  margin: '5 15 15 20',
				      scale: 'large',
				      width: 100,
				      text: 'Cancelar',
					  //disabled: true,
					  handler: function() {
						  window.location = baseURL+'/actividad/actividad-tipo/index-ui';
					}
		 	      }
			    ]
		     }],
			});
		
		
		var pantalla = Ext.create('Ext.panel.Panel', {
		    //title: ' ',
		    width: 'fit',
		    height: 570,
		    items:[pantallaActividad],
		    listeners:{
				'render':function(){
					Ext.getCmp('topTabPanel').setActiveTab(1);
//					Ext.getCmp('actividadTabPanel').setActiveTab(1);
				}
			}
		});
		cargarDatos();
		Ext.getCmp('centerPanel').add(pantalla);
});

			
		</script>
    </head>
    <body>
    </body>
</html>
