<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Tipo de Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';
	
			var itemsPorPagina = 10;
			var page = 0;

			var aux;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		var cargarDatos = function (){
			aux = buscarId();
			Ext.Ajax.request({
			    url: baseURL +'/actividad/actividad-tipo/get',
			    params: {
			        'id': aux,
			    },
			    success: function(response) {
			    	var campos = Ext.decode(response.responseText);
			    	var form = Ext.getCmp('form').getForm();
			    	
			    	for (campo in campos) {
				    	var name = form.findField(campo);
				    		if (name) {
				    			 if (campo == "homologada" || campo == "activo")
							     {
								    	if (campos[campo] == 1){
								    		campos[campo] = 'Si';
								    	}
								    	else if (campos[campo] == 0){
								    		campos[campo] = 'No';
								    	}
					 			    	name.setValue(campos[campo]);
								 } else if (campo == "modalidad")
							     {
								    	if (campos[campo] == 'D'){
								    		campos[campo] = 'D&iacute;as de Formaci&oacute;n';
								    	}
								    	else if (campos[campo] == 'H'){
								    		campos[campo] = 'Horas de Formaci&oacute;n';
								    	}
								    	name.setValue(campos[campo]);
								 } else{
								    
									    name.setValue(campos[campo]);
							     }
					    }	}	
			    	}
			   
				});
		};

		var pantallaActividad = Ext.create('Ext.form.Panel', {
			id: 'form',
			items:[{
			    xtype: 'panel',
			    bodyStyle: {
		        	background: '#C8CED8',
		        },
			    title: 'Tipo de Actividad',
			    //collapsible: true,
			    //anchor:'90%',
			    height: 'fit',
			    width: 'fit',
			    border: 1,
			    padding: 10,
			    layout: 'hbox',
			    defaultType: 'textfield',
			    items: [{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'textfield',
					items: [    
					    {
						    	xtype: 'displayfield',
						        fieldLabel: 'Nombre',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'titulo',
						},{
						    	xtype: 'displayfield',
						        fieldLabel: 'Activo',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'activo',
						},{
						    	xtype: 'displayfield',
						        fieldLabel: 'Descripci&oacute;n',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'descripcion',
						}
			    	]},{
					xtype: 'container',
					flex: 1,
					layout: 'anchor',
					defaultType: 'textfield',
					items: [{
						        fieldLabel: 'Modalidad',
					        	xtype: 'displayfield',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
					 	        name: 'modalidad',
				    	 	},{
						    	xtype: 'displayfield',
						        fieldLabel: 'Homologada',
						        padding: 15,
						        labelWidth: 110,
						        anchor:'90%',
						        name: 'homologada',
							}
			    	]}]},{
		    	xtype: 'container',
		 	    height: 200,
		 	    width: 'fit',
		 	   layout: 'hbox',
		 	   // flex: 1,
		 	   // padding: '5 0 10 440',
		 	    items:[
				  { xtype: 'tbfill' },
		 	      {	  
		 	    	  xtype: 'button',
		 	    	  margin: '5 0 15 0',
				      scale: 'large',
				      width: 100,
				      text: 'Editar',
				      handler: function() {
	                   		var url = baseURL+'/actividad/actividad-tipo/editar-ui#?id='+aux;  
	                   		window.location = url;     
				      }
		 	      },{
		 	    	  xtype: 'button',
		 	    	  margin: '5 15 15 20',
				      scale: 'large',
				      width: 100,
				      text: 'Volver',
					  //disabled: true,
					  handler: function() {
						  window.location = baseURL+'/actividad/actividad-tipo/index-ui';
					}
		 	      }
			    ]
		     }],
			});
		
		
		var pantalla = Ext.create('Ext.form.Panel', {
		    //title: ' ',
		    width: 'fit',
		    height: 570,
		    items:[pantallaActividad],
		    listeners:{
				'render':function(){
					Ext.getCmp('topTabPanel').setActiveTab(1);
//					Ext.getCmp('actividadTabPanel').setActiveTab(1);
				}
			}
		});
		cargarDatos();
		Ext.getCmp('centerPanel').add(pantalla);
});

			
		</script>
    </head>
    <body>
    </body>
</html>
