<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Tipo de Actividad</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxnombre = null;
			var auxcodigo = null;
			var auxnivel = null;
			var auxmodalidad = null;
			var auxcriterio = null;
	
			var itemsPorPagina = 10
			var page = 0;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('actividadTipo', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_actividad_tipo_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'codigo'
				},{
					type: 'string',
					name: 'atelier'
				},{
					type: 'string',
					name: 'asistencia'
				},{
					type: 'float',
					name: 'duracion'
				},{
					type: 'string',
					name: 'nivel'
				},{
					type: 'string',
					name: 'modalidad'
				},{
					type: 'string',
					name: 'criterio'
				}
			]
		});

		Ext.define('nivel', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_nivel_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'descripcion'
				}
			]
		});

		Ext.define('modalidad', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_modalidad_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'descripcion'
				}
			]
		});

		Ext.define('criterio', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_criterio_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'codigo'
				},{
					type: 'float',
					name: 'horas'
				},{
					type: 'date',
					name: 'fecha_alta'
				},{
					type: 'date',
					name: 'fecha_baja'
				}
			]
		});
		
	var nivelStore = createStore('nivel', baseURL, '/actividad/combos/act-nivel',"{'p[limit]':'all'}");
	var modalidadStore = createStore('modalidad', baseURL, '/actividad/combos/act-modalidad',"{'p[limit]':'all'}");
	var criterioStore = createStore('criterio', baseURL, '/actividad/combos/act-criterio',"{'p[limit]':'all'}");
	var actividadTipoStore = createStorePage('actividadTipo', baseURL, '/actividad/actividad-tipo/index', page, itemsPorPagina);
	
	var comboNivel = createCombo ('Nivel',50,180,nivelStore,'nombre','act_nivel_id','local','0 10 5 0','90%','nivel');
	var comboModalidad = createCombo ('Modalidad',80,200,modalidadStore,'nombre','act_modalidad_id','local','0 10 5 0','90%','modalidad');
	var comboCriterio = createCombo ('Criterio',70,280,criterioStore,'nombre','act_criterio_id','local','0 10 5 0','90%','criterio');
		  
		var panelFiltros = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 collapsible: true,
			 title:'Filtros de B&uacute;squeda',
			    width: 'fit',	
			    height: 'fit',			           
			    items:[
				{
				    xtype: 'container',
				    id: 'filtros',
				    height: 40,
				    layout:'hbox',
				    items:[{   	
					    		xtype: 'textfield',
						        fieldLabel: 'Nombre',
						        padding: '10 0 5 15',
						        labelWidth: 70,
						        layout:'anchor',
						        anchor:'90%',
						        name: 'nombre',
							    flex: 0.5    
				    	  },{   	
					    		xtype: 'textfield',
						        fieldLabel: 'C&oacute;digo',
						        padding: '10 0 5 20',
						        labelWidth: 60,
						        layout:'anchor',
						        anchor:'90%',
						        name: 'codigo',
							    flex: 0.4    
				    	  },{
							    xtype: 'container',
							    padding: '10 0 0 20',
							    layout:'anchor',
							    flex: 0.5,
							    items: [comboNivel]
						   }, 
				    	   {
						        xtype: 'container',
						        padding: '10 0 0 0', 
						        layout:'anchor',
						        flex: 0.5,
						        items: [comboModalidad]
					    	},
					    	{
						        xtype: 'container',
						        padding: '10 0 0 0',
						        layout:'anchor', 
						        flex: 0.65,
						        items: [comboCriterio]
					    	}
					   ]
					},{
						xtype: 'container',
					    height: 45,
					    layout:'hbox',
					    items:[{
			
				           		xtype: 'button',
				           		width: 100,
				           		margin: '5 0 0 20',
				            	text: 'Filtrar',
					            scale   : 'medium',
					            handler: function(b,e) {
					            	
							           var basicForm = b.up('form').getForm();						
							           var valoresForm = basicForm.getFieldValues();

					           		    var auxnombre = valoresForm.nombre;
					           		    var auxcodigo = valoresForm.codigo;
					           			
							           	auxnivel = valoresForm.nivel;
							           	auxmodalidad = valoresForm.modalidad;
							           	auxcriterio = valoresForm.criterio;
			
										//inicializo los pages
							           	page = 0;
										gridActividadTipo.store.currentPage = 1;
										
						                actividadTipoStore.load({
											params: {
												"s[nombre]": auxnombre,
												"s[codigo]": auxcodigo,
												"s[nivel]": auxnivel,
												"s[modalidad]": auxmodalidad,
												"s[criterio]": auxcriterio
									   		} 
						               });
						            }//end of handler  
									        
								},{
			
								  		xtype: 'button',
								  		width: 100,
								  		margin: '5 0 0 15',
					               		text: 'Limpiar',
						           		scale   : 'medium',
						           		handler: function(b,e) {
						           			//inicializo los pages
								           	page = 0;
											gridActividadTipo.store.currentPage = 1;
											//console.log(this);
						           			b.up('form').getForm().reset();
						           			actividadTipoStore.load();						   	
				           		  		}
								}]}
				    	]
		});
    	
		var gridActividadTipo = Ext.create('Ext.grid.Panel', {
            //title: 'Tipo de Actividades',
            selModel: {
                checkOnly: true,
                injectCheckbox: 1
            },
            width: 'fit',
            padding: 10,
            height: 385,
            region: 'center',  
	           dockedItems: [
	                {     
		          	     xtype: 'toolbar',
                         dock: 'top',
                         items: [
                         { 
                             xtype: 'tbfill' 
                         },{
     			            xtype: 'button',	
    			            text: 'Crear Tipo de Actividad',
    			            handler: function() {
    			            	window.location = baseURL+'/actividad/actividad-tipo/crear-ui';
    						}
    		            }]
	                }
	                ,{
                    xtype: 'pagingtoolbar',
                    store: actividadTipoStore, 
                    dock: 'bottom',
                    displayInfo: true,
                    listeners: {
                        'afterrender': function (component)
                        {
                            component.down('#refresh').hide()
                        },single: true
                    },
                    displayMsg: 'Registro {0} al {1} de {2}',
                    beforePageText: 'P&aacute;gina',
                    afterPageText : 'de {0}',
                    moveNext : function(){ 
                   		page = page + itemsPorPagina;
                   	 	this.store.currentPage++;
           				actividadTipoStore.load({
	       				    params:{
								"s[nombre]": auxnombre,
								"s[codigo]": auxcodigo,
	       				    	"p[limit]": itemsPorPagina,
	       						"p[page]": page,
								"s[nivel]": auxnivel,
								"s[modalidad]": auxmodalidad,
								"s[criterio]": auxcriterio
	       				    }
       					});
           					console.log("page store: ", page);
          				    console.log("page extjs: ",this.store.currentPage);	
                	 },
                 	 movePrevious : function(){ 
                 		page = page - itemsPorPagina;
						this.store.currentPage--;
						actividadTipoStore.load({
		   				    params:{
								"s[nombre]": auxnombre,
								"s[codigo]": auxcodigo,
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
								"s[nivel]": auxnivel,
								"s[modalidad]": auxmodalidad,
								"s[criterio]": auxcriterio	        
		   				    }
   						});
	       					console.log("page store: ", page);
	      				    console.log("page extjs: ",this.store.currentPage);	
            		 },
             		moveFirst : function(){ 
             			page = 0;
						this.store.currentPage = 1;
						actividadTipoStore.load({
		   				    params:{
								"s[nombre]": auxnombre,
								"s[codigo]": auxcodigo,
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
								"s[nivel]": auxnivel,
								"s[modalidad]": auxmodalidad,
								"s[criterio]": auxcriterio  
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);	
            	 	},
            	 	moveLast : function(){                 	 	
            	 		if (this.getStore().getTotalCount() % itemsPorPagina == "0"){
	                	 	page = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)-1)*itemsPorPagina;
	                	 	this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina));
            	 		}
						else
						{
							page = parseInt(this.getStore().getTotalCount() / itemsPorPagina)*itemsPorPagina;
							this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)+1);
						}
            	 		actividadTipoStore.load({
		   				    params:{
								"s[nombre]": auxnombre,
								"s[codigo]": auxcodigo,
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
								"s[nivel]": auxnivel,
								"s[modalidad]": auxmodalidad,
								"s[criterio]": auxcriterio 
		   				    }
   						});
       					console.log("page store: ", page);
      				    console.log("page extjs: ",this.store.currentPage);         					
            	 	},
                }
	                ],                       
            layout: 'fit',
            emptyText: "No existen tipo de actividades cargadas",
            
            store: actividadTipoStore,
            loadMask: true,
            // grid columns
            columns:[{
                text: "Tipo de Actividad",
                dataIndex: 'nombre',
                align: 'left',
                flex: 2.2,
                renderer: function(val, metadata, record, otraCosa, otraCosaMas) {
                    console.log(metadata);
                    return '<a href="'+baseURL+'/actividad/actividad-tipo/get-ui#?id=' + metadata.record.data.act_actividad_tipo_id +'">'+ val +'</a>';
            	}
            },{
                text: "C&oacute;digo",
                dataIndex: 'codigo',
                align: 'center',
                flex: 1,
            },{
                text: "Atelier",
                dataIndex: 'atelier',
                align: 'center',
                flex: 0.6,
            },{
                text: "Asistencia",
                dataIndex: 'asistencia',
                align: 'center',
                flex: 0.6,
            },{
                text: 'Duraci&oacute;n (hs)',
                dataIndex: 'duracion',
                align: 'center',
                flex: 0.5,
            },{
                text: "Nivel",
                dataIndex: 'nivel',
                align: 'center',
                flex: 0.5,
            },{
                text: "Modalidad",
                dataIndex: 'modalidad',
                align: 'center',
                flex: 0.5,
            },{
                text: "Criterio",
                dataIndex: 'criterio',
                align: 'center',
                flex: 0.4,
            },{
                xtype:'actioncolumn',
                width:35,
                align: 'center',
                items: [{
                    icon: baseURL+'/img/icons/grid/edit.png',  
                    tooltip: 'Edit',
               		handler: function(grid, rowIndex, colIndex) {
                   		var url = baseURL+'/actividad/actividad-tipo/editar-ui#?id='+actividadTipoStore.getAt(rowIndex).get('act_actividad_tipo_id');  
                   		window.location = url;                     
                    }
                }]
            },{
                xtype:'actioncolumn',
                width: 35,
                align: 'center',
                items: [{
                	icon: baseURL+'/img/icons/grid/delete.png',  
                    //tooltip: 'Delete',
                    handler: function(grid, rowIndex, colIndex) {
                    	var id_delete = actividadTipoStore.getAt(rowIndex).get('act_actividad_tipo_id');
                    	var nombre_delete = actividadTipoStore.getAt(rowIndex).get('nombre');
                    	var auxmensaje = 'Confirma que desea borrar el Tipo de Actividad '+nombre_delete+'?';
                    	Ext.Msg.show({
                            title:'Consulta',
                            msg: auxmensaje,
                            width: 250,
                            buttons: Ext.Msg.YESNO,
                            icon: Ext.Msg.QUESTION,
                            fn: function(rec) {
                               if (rec === "yes") {
                            	   Ext.Ajax.request({
        							   url: baseURL + '/actividad/actividad-tipo/delete',
        							   success: function(response, opt){
        								   Ext.Msg.show({
        									    title:'Aviso',
        										msg:'Tipo de Actividad Borrado Correctamente'
        								   });
        								   function hide_message() {
        								       Ext.defer(function() {
        								           Ext.MessageBox.hide();
        								       }, delay);
        								   }
        								   hide_message();
        								   actividadTipoStore.load();
        							   },
        							   jsonData:{
        							       'delete':{
												'act_actividad_tipo_id': id_delete,
        							       }
        							   }
        						 });
                              }
                               else{
                            	   this.close();
                               }	                               
                           }
                       });

                    	
                        
                    }
                }]
            }       
            ]
            	        	
		 });

		 
			
		var pantalla = Ext.create('Ext.panel.Panel', {
		    width: 'fit',
		    height: 510,
		    items:[
		         {	
		        	 xtype: 'panel',
					 items: [panelFiltros]
			        
		         },{
		        	 xtype: 'container',
					 items: [gridActividadTipo]
		         }
		    ],
		    listeners:{
				'render':function(){
					Ext.getCmp('topTabPanel').setActiveTab(1);
					Ext.getCmp('actividadTabPanel').setActiveTab(1);
				}
			}
		});

			Ext.getCmp('centerPanel').add(pantalla);


				
});

			
		</script>
    </head>
    <body>
    </body>
</html>
