<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Profesion</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>

		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxprofesion = null;
	
			var itemsPorPagina = 11;
			var page = 0;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('profesion', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'org_profesion_id'
				},
				{
					type: 'string',
					name: 'nombre'
				}
				,
				{
					type: 'string',
					name: 'abrev'
				}
			]
		});
		
		var profesionStore = Ext.create('Ext.data.Store', {
			model: 'profesion',
			pageSize: itemsPorPagina, 
			proxy: {
				type: 'ajax',
				  extraParams:{
				    	"p[limit]": itemsPorPagina,
						"p[page]": page, 
				  },
				headers: {'Accept':'application/json'},
				url: baseURL + '/org/profesion/index?format=json',
				reader: {
					type: 'json',
					root: 'records',
					totalProperty: 'numResults'
				}
			},
			autoLoad: true
		});

		function agregarwindow() {
			 
            var form = Ext.widget('form', {
                layout: {
                    type: 'vbox',
                    align: 'stretch'
                },
                border: false,
                bodyPadding: 10,

                fieldDefaults: {
                    labelAlign: 'top',
                    labelWidth: 100,
                    labelStyle: 'font-weight:bold'
                },
                items: [
                       {
                    xtype: 'textfield',
                    fieldLabel: 'Nombre de la Profesi&oacute;n',   
                    allowBlank: false,
                    name: 'nombre',   
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Abreviaci&oacute;n',
                    allowBlank: true,
                    name: 'abrev',   
                }],

                buttons: [{
                    text: 'Agregar',
                    handler: function(b,e) {
                    	var basicForm = b.up('form').getForm();  						
			            var valoresForm = basicForm.getFieldValues();

			           	var auxnombre = valoresForm.nombre;
			           	var auxabrev = valoresForm.abrev;
	
						Ext.Ajax.request({
							   url: baseURL + '/org/profesion/post',
							   success: function(response, opt){
								   Ext.Msg.show({
									    title:'Aviso',
										msg:'Profesi&oacute;n Cargada Correctamente',
										closable: false,
										width: 250
								   });
								   function hide_message() {
								       Ext.defer(function() {
								           Ext.MessageBox.hide();
								       }, delay);
								   }
								   hide_message();
								   Ext.getCmp('filtros').up('form').getForm().reset();
								   auxprofesion = null;
								   profesionStore.load();
							   },
							   jsonData:{
							       'post':{
									   'nombre': auxnombre,
									   'abrev': auxabrev,
							       }
							   }
						 });
						 this.up('window').close();
                    }
                },{
                    text: 'Cancelar',
                    handler: function() {
                        this.up('form').getForm().reset();
                        this.up('window').close();
                    }
                }]
            });

            win = Ext.widget('window', {
                title: 'Agregar Profesi&oacute;n',
                closeAction: 'hide',
                width: 400,
                height: 200,
                layout: 'fit',
                resizable: true,
                modal: true,
                items: form
            }); 
       	 win.show();
    	}  

		function editarwindow (id_edit, nombre_edit, abrev_edit) {
			 
            var form = Ext.widget('form', {
                layout: {
                    type: 'vbox',
                    align: 'stretch'
                },
                border: false,
                bodyPadding: 10,

                fieldDefaults: {
                    labelAlign: 'top',
                    labelWidth: 100,
                    labelStyle: 'font-weight:bold'
                },
                items: [
                       {
                    xtype: 'textfield',
                    fieldLabel: 'Nombre de la Profesi&oacute;n',   
                    allowBlank: false,
                    value: nombre_edit,
                    name: 'nombre',   
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Abreviaci&oacute;n',
                    allowBlank: true,
                    value: abrev_edit,
                    name: 'abrev',   
                }],

                buttons: [{
                    text: 'Guardar',
                    handler: function(b,e) {
                    	var basicForm = b.up('form').getForm();  						
			            var valoresForm = basicForm.getFieldValues();

			           	var auxnombre = valoresForm.nombre;
			           	var auxabrev = valoresForm.abrev;
	
						Ext.Ajax.request({
							   url: baseURL + '/org/profesion/put',
							   success: function(response, opt){
								   Ext.Msg.show({
									    title:'Aviso',
										msg:'Profesi&oacute;n Modificada Correctamente',
										closable: false,
										width: 250
								   });
								   function hide_message() {
								       Ext.defer(function() {
								           Ext.MessageBox.hide();
								       }, delay);
								   }
								   hide_message();
								   Ext.getCmp('filtros').up('form').getForm().reset();
								   auxprofesion = null;
								   profesionStore.load();
							   },
							   jsonData:{
							       'put':{
							    	   'org_profesion_id': id_edit,
									   'nombre': auxnombre,
									   'abrev': auxabrev,
							       }
							   }
						 });
						 this.up('window').close();
                    }
                },{
                    text: 'Cancelar',
                    handler: function() {
                        this.up('form').getForm().reset();
                        this.up('window').close();
                    }
                }]
            });

            win = Ext.widget('window', {
                title: 'Editar Profesi&oacute;n',
                closeAction: 'hide',
                width: 400,
                height: 200,
                layout: 'fit',
                resizable: true,
                modal: true,
                items: form
            }); 
       	 win.show();
    	}  

		var panelFiltros = Ext.create('Ext.form.Panel', {
			 type:  'hbox',
			 collapsible: true,
			 title:'Filtros de B&uacute;squeda',
			    width: 'fit',	
			    height: 'fit',			           
			    items:[
				{
				    xtype: 'container',
				    id: 'filtros',
				    height: 40,
				    layout:'column',
				    items:[{   	
					    		xtype: 'textfield',
						        fieldLabel: 'Nombre',
						        padding: '10 0 5 15',
						        labelWidth: 70,
						        width: 400,
						        layout:'anchor',
						        anchor:'90%',
						        name: 'nombre',       
				    	  }
					   ]
					},{
						xtype: 'container',
					    height: 45,
					    layout:'hbox',
					    items:[{
			
				           		xtype: 'button',
				           		width: 100,
				           		margin: '5 0 0 20',
				            	text: 'Filtrar',
					            scale   : 'medium',
					            handler: function(b,e) {
					            	
							           var basicForm = b.up('form').getForm();						
							           var valoresForm = basicForm.getFieldValues();

										auxprofesion = valoresForm.nombre;
										
							           //inicializo los pages
							           	page = 0;
										gridProfesion.store.currentPage = 1;
										
						                profesionStore.load({
											params: {
												"s[nombre]": auxprofesion
									   		} 
						               });
						            }//end of handler  
									        
								},{
			
								  		xtype: 'button',
								  		width: 100,
								  		margin: '5 0 0 15',
					               		text: 'Limpiar',
						           		scale   : 'medium',
						           		handler: function(b,e) {
						           			//inicializo los pages
								           	page = 0;
								           	auxprofesion = null;
											gridProfesion.store.currentPage = 1;
						           			b.up('form').getForm().reset();
						           			profesionStore.load();						   	
				           		  		}
								}]}
				    	]
		});	
		
		var gridProfesion = Ext.create('Ext.grid.Panel', {
            //title: 'Profesi&oacute;n',
            selModel: {
                checkOnly: true,
                injectCheckbox: 1
            },
            width: 'fit',
            padding: 10,
            height: 410,
            region: 'center',  
	           dockedItems: [
	                {     
		          	     xtype: 'toolbar',
                         dock: 'top',
                         items: [
                         { 
                             xtype: 'tbfill' 
                         },{
                        	xtype: 'button',	
     			            text: 'Agregar',
     		                handler: agregarwindow,
                         }]
	                }
	                ,{
                    xtype: 'pagingtoolbar',
                    store: profesionStore, 
                    dock: 'bottom',
                    displayInfo: true,
                    listeners: {
                        'afterrender': function (component)
                        {
                            component.down('#refresh').hide()
                        },single: true
                    },
                    displayMsg: 'Registro {0} al {1} de {2}',
                    beforePageText: 'P&aacute;gina',
                    afterPageText : 'de {0}',
                    moveNext : function(){ 
                   		page = page + itemsPorPagina;
                   	 	this.store.currentPage++;
           				profesionStore.load({
	       				    params:{
	       				    	"p[limit]": itemsPorPagina,
	       						"p[page]": page, 
	       						"s[nombre]": auxprofesion       
	       				    }
       					});
                	 },
                 	 movePrevious : function(){ 
                 		page = page - itemsPorPagina;
						this.store.currentPage--;
						profesionStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page, 
		   						"s[nombre]": auxprofesion	        
		   				    }
   						});
            		 },
             		moveFirst : function(){ 
             			page = 0;
						this.store.currentPage = 1;
						profesionStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   						"s[nombre]": auxprofesion 	        
		   				    }
   						});
            	 	},
            	 	moveLast : function(){                 	 	
            	 		if (this.getStore().getTotalCount() % itemsPorPagina == "0"){
	                	 	page = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)-1)*itemsPorPagina;
	                	 	this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina));
            	 		}
						else
						{
							page = parseInt(this.getStore().getTotalCount() / itemsPorPagina)*itemsPorPagina;
							this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)+1);
						}
            	 		profesionStore.load({
		   				    params:{
		   				    	"p[limit]": itemsPorPagina,
		   						"p[page]": page,
		   						"s[nombre]": auxprofesion		        
		   				    }
   						});       					
            	 	},
                }
	                ],                       
            layout: 'fit',
            emptyText: "No existen profesiones cargadas",
            
            store: profesionStore,
            loadMask: true,
            // grid columns
            columns:[{
                text: "Profesi&oacute;n",
                dataIndex: 'nombre',
                align: 'left',
                flex: 1,
            },{
                text: "Abreviaci&oacute;n",
                dataIndex: 'abrev',
                align: 'center',
                flex: 1,
            },{
                xtype:'actioncolumn',
                width:35,
                align: 'center',
                items: [{
                    icon: baseURL+'/img/icons/grid/edit.png',  
                    //tooltip: 'Edit',
                handler: function(grid, rowIndex, colIndex) {
                    	var id_edit = profesionStore.getAt(rowIndex).get('org_profesion_id');
                    	var nombre_edit = profesionStore.getAt(rowIndex).get('nombre');
                    	var abrev_edit = profesionStore.getAt(rowIndex).get('abrev');
						editarwindow(id_edit, nombre_edit, abrev_edit);                        
                    }
                }]
            },{
                xtype:'actioncolumn',
                width: 35,
                align: 'center',
                items: [{
                	icon: baseURL+'/img/icons/grid/delete.png',  
                    //tooltip: 'Delete',
                    handler: function(grid, rowIndex, colIndex) {
                    	var id_delete = profesionStore.getAt(rowIndex).get('org_profesion_id');
                    	var nombre_delete = profesionStore.getAt(rowIndex).get('nombre');
                    	var auxmensaje = 'Confirma que desea borrar la profesion '+nombre_delete+'?';
                    	Ext.Msg.show({
                            title:'Consulta',
                            msg: auxmensaje,
                            width: 250,
                            buttons: Ext.Msg.YESNO,
                            icon: Ext.Msg.QUESTION,
                            fn: function(rec) {
                               if (rec === "yes") {
                            	   Ext.Ajax.request({
        							   url: baseURL + '/org/profesion/delete',
        							   success: function(response, opt){
        								   Ext.Msg.show({
        									    title:'Aviso',
        										msg:'Profesi&oacute;n Borrada Correctamente',
        										closable: false,
        										width: 250
        								   });
        								   function hide_message() {
        								       Ext.defer(function() {
        								           Ext.MessageBox.hide();
        								       }, delay);
        								   }
        								   hide_message();
        								   Ext.getCmp('filtros').up('form').getForm().reset();
        								   auxprofesion = null;
        								   profesionStore.load();
        							   },
        							   jsonData:{
        							       'delete':[
        							    	id_delete
        							       ]
        							   }
        						 });
                              }
                               else{
                            	   this.close();
                               }	                               
                           }
                       });

                    	
                        
                    }
                }]
            }       
            ]
            	        	
		 });

		 
			
		var pantalla = Ext.create('Ext.panel.Panel', {
			//id: 'margen',
		    //title: ' ',
		    width: 'fit',
		    height: 550,
		    items:[
			         {	
			        	 xtype: 'panel',
						 items: [panelFiltros]
				        
			         },{
			        	 xtype: 'container',
						 items:[gridProfesion],
			         }
			],
		    listeners:{
				'render':function(){
					Ext.getCmp('topTabPanel').setActiveTab(0);
					Ext.getCmp('personaTabPanel').setActiveTab(1);
				}
			}
		});
			
		Ext.getCmp('centerPanel').add(pantalla);

				
});

			
</script>
		
    </head>
    <body>
    </body>
</html>
