<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Paraguay</title>
        <link rel="stylesheet" href="<?=$this->basePath();?>/ext-4.2/resources/css/ext-all-neptune2.css"/>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/ext-4.2/ext-all.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/ext-4.2/locale/ext-lang-es.js"></script>

		<style type="text/css">

			.panel{
				margin: 0px;
				margin-top: 0px;
				margin-bottom: 0px;
				padding-top: 5px;
				padding-bottom: 5px;
				padding-left: 10px;
				font-weight: bold;
				font-size: 18px;
				color: black;
				background: white;
			}
			
			.panelover{
				margin: 0px;
				margin-top: 0px;
				margin-bottom: 0px;
				padding-top: 5px;
				padding-bottom: 5px;
				padding-left: 10px;
				font-weight: bold;
				font-size: 18px;
				color: red;
				background: green;
			}
			
			.tabs 
			{
				font-weight: bold;
				font-size: 18px;
				border-color: white;
				color: #157fcc;
				text-align: center;
				background: white;	
			}

			.tabsover
			{
				font-weight: bold;
				font-size: 18px;
				border-color: white;
				color: red;
				text-align: center;	
			}
		

        </style>
		
		<script type="text/javascript">

		var baseURL = '<?=$this->basePath()?>';
		var logout = baseURL + '/login/leave';

		var menuPersona = Ext.create('Ext.tab.Panel', {
			 anchor:'90%',
		    height: '500',
		    plain: true, 
		    layout: {
	            pack : 'center',
	            align: 'center'
	        },
		    renderTo: document.body,
		    items: [{
		        title: 'Personas',
// 		        listeners: {
// 			        activate: function() {
// 				        var urlaux = baseURL+'/org/personas/index-ui';
// 				        console.log(window.location.pathname);
// 				        console.log(urlaux);
// 				        if (window.location.pathname != baseURL+'/org/personas/index-ui')
// 				        {    
// 				            	Ext.Ajax.request({
// 				            	    url: '/prh/org/personas/index-ui',
// 				            	    method: 'GET',
// 				            	    success: function(response, options){
// 					            	   var htmlResponse = response.responseText;
// 				            	       var destino = Ext.getCmp('centerPanel');
// 				            	       console.log(destino);
// 				            	       if(destino)
// 				            	       {
// 				            	    	   destino.getEl().update(htmlResponse, true, function(a,b,c){
// 												console.log(a,b,c);
// 					                   	    });
// 				            	       }
// 				            	       window.location = baseURL+'/org/personas/index-ui'
// 				            	    },
// 				            	    failure: function(response,options){
// 										Ext.Msg.alert('Aviso','Hubo un error al cargar la pagina.');
// 						           	}
// 				            	});
// 				         }     	
// 	            	}
//		        }
		    },{
		        title: 'Profesi&oacute;n',
		    },{
		        title: 'Religi&oacute;n',
		    },{
		        title: 'Estado Civil',
		    },{
		        title: 'Tipo de Documento',
		    },{
		        title: 'Rol',
		    },{
		        title: 'Relaci&oacute;n',
		    },{
		        title: 'Tipo de Contacto',
		    }]
		});
		
		var menuActividad = Ext.create('Ext.tab.Panel', {
			anchor:'90%',
		    height: 'fit',
		    plain: true,
		    renderTo: document.body,
		    items: [{
		        title: 'Actividad',
		       // items: [tabActividad],
		    },{
		        title: 'Tipo de Actividad',
		    },{
		        title: 'Nivel',
		    },{
		        title: 'Modalidad',
		    },{
		        title: 'Criterio',
		    },{
		        title: 'Tarifas',
		    }]
		});
		
		
			
		    var pantalla = Ext.create('Ext.tab.Panel', {
				//title: 'Hoola',
		    	anchor:'90%',
				height: 'fit',
				activeTab: 0,
				autoScroll: true,
				border: 0,
				plain: false,
				buttonAlign: 'center',
				renderTo: document.body,
				items: [{
					    title: 'Persona',
					    items:[menuPersona],
					},{
					    title: 'Actividad',
					    items:[menuActividad],
					},{
					    title: 'Calendario',
					},{
					    title: 'Stock',
					},{
					    title: 'Aporte',
					},{
					    title: 'Balance',
					},{
					    title: 'Presupuesto',
					},{
					    title: 'Estad&iacute;stica',
				}]
			});
		
		Ext.onReady(function(){
			
			Ext.create('Ext.container.Viewport', {
			    layout: 'border',
			    items: [{
			        region: 'north',
			        title: 'Atilio Nicolini - Formador',
			        collapsible: true,
			        anchor:'90%',
			        collapsed:true,
			        bodyStyle: {
			        	background: 'white',
			        	width: '100%',
			        	height: '100%',
			        },
			        border: 0,
			        height: 140,
			        //maxHeight: 205,
			        layout: 'hbox',
			        items:[
			        {
			        	xtype: 'panel',
			        	flex: 0.3,
			    	    width: '300',
			    	    height: 'fit',
			    	    border: 0,
			             padding: '0 0 0 0',
			             defaultType: 'textfield',
			             items: [ 
			    					{	
			    						 xtype: 'container',
			    						  style: 'text-align:left',
			    						  padding: 10,
			    						  items: [{
			    						      xtype: 'button',
			    						      scale: 'large',
			    						      text: 'SALIR',
			    								width:90,
			    								//disabled: true,
			    								handler: function() {
			    						      	window.location = logout; 
			    								}
			    						  }]
			    					}
			    		  ]
			        	
			        },{
			    	    xtype: 'container',
			    	    flex: 1,
			    	    padding: '0 10 10 10',
			    	    layout: 'anchor',
			    	    defaultType: 'textfield',
			    	    items: Ext.create('Ext.Img', {
				            src: baseURL + '/img/prh-layout.png',
				            padding: '0 0 0 820',
				        })}]
			    },
// 			    {
// 			        region: 'south',
// 			      //  title: 'PRH - PARAGUAY',
// 			        baseCls: 'completo',
// 			       // collapsible: true,
// 			       // html: 'Information goes here',
// 			        bodyStyle: {
// 			        	background: '#112D6F',
// 			        },
// 			        border: 0,
// 			        height: 30,
// 			        maxHeight: 30,
// 			    }, 
			   {
			        region: 'center',
			        //anchor:'90%',
			        height:'fit',
			        items:[pantalla],
    
			    }]
			});
			

		});//onready
			
		</script>
    </head>
    <body id='bodyHTML'>
       <?php echo $this->content; ?>
    </body>
</html>
		