<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Paraguay</title>
        <link rel="stylesheet" href="<?=$this->basePath();?>/ext-4.2/resources/css/ext-all-neptune2.css"/>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/ext-4.2/ext-all.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/ext-4.2/locale/ext-lang-es.js"></script>
		<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/formatearFecha.js"></script>

		<style type="text/css">

			.panel{
				margin: 0px;
				margin-top: 0px;
				margin-bottom: 0px;
				padding-top: 5px;
				padding-bottom: 5px;
				padding-left: 10px;
				font-weight: bold;
				font-size: 18px;
				color: black;
				background: white;
			}
			
			.panelover{
				margin: 0px;
				margin-top: 0px;
				margin-bottom: 0px;
				padding-top: 5px;
				padding-bottom: 5px;
				padding-left: 10px;
				font-weight: bold;
				font-size: 18px;
				color: red;
				background: green;
			}
			
			.tabs 
			{
				font-weight: bold;
				font-size: 18px;
				border-color: white;
				color: #157fcc;
				text-align: center;
				background: white;	
			}

			.tabsover
			{
				font-weight: bold;
				font-size: 18px;
				border-color: white;
				color: red;
				text-align: center;	
			}
		

        </style>
		
		<script type="text/javascript">

		var baseURL = '<?=$this->basePath()?>';
		var logout = baseURL + '/login/leave';
		var usuario_logueado = '<?php echo $this->logged_user(); ?>';
		var delay = 2000;

		var verURL = function(){
			if (window.location) {
			    var auxurl = (window.location.pathname).split("prh/");
			    var auxpath = (auxurl[1]).split("/");
		        var path = '/'+auxpath[0]+'/'+auxpath[1];
			    console.log(path);
 					return path;
			}
		};
		
		var menuPersona = Ext.create('Ext.tab.Panel', {
		   autoHeight:true,
		    plain: true, 
		    //style:{border:'none !important'},
		    style:'background-color: #C8CED8',
		    //border: false,
		    id: 'personaTabPanel',
		    //frame:false,
		    //renderTo: document.body,
		    items: [{
		        title: 'Personas',
		        tabConfig: {style:'width:120px'},
		        pathName: '/org/personas/index-ui',
/* esto tenes que descomentar, pero cuando haces eso el layout te lleva
a esta pagina por el active predeterminado de la tabla, parece que re asigna el tab*/		        
// 		        listeners: {
// 			        activate: function() {
// 			        	var url = verURL(); 
// 				        if (url != '/org/personas')
// 				        {    
// 					        console.log("prueba");
// 				            	Ext.Ajax.request({
// 				            	    url: '/prh/org/personas/index-ui',
// 				            	    method: 'GET',
// 				            	    success: function(response, options){
// 					            	   var htmlResponse = response.responseText;
// 				            	       var destino = Ext.getCmp('centerPanel');
// 				            	       console.log(destino);
// 				            	       if(destino)
// 				            	       {
// 				            	    	   destino.getEl().update(htmlResponse, true, function(a,b,c){
// 												console.log(a,b,c);
// 					                   	    });
// 				            	       }
// 				            	       window.location = baseURL+'/org/personas/index-ui'
// 				            	    },
// 				            	    failure: function(response,options){
// 										Ext.Msg.alert('Aviso','Hubo un error al cargar la pagina.');
// 						           	}
// 				            	});
// 				         }     	
// 	            	}
// 		        }
		    },{
		        title: 'Profesi&oacute;n',
		        tabConfig: {style:'width:120px'},
		        pathName: '/org/profesion/index-ui'
		    },{
		        title: 'Religi&oacute;n',
		        tabConfig: {style:'width:120px'},
		        pathName: '/org/religion/index-ui'
		    },{
		        title: 'Estado Civil',
		        tabConfig: {style:'width:120px'},
		        pathName: '/org/estado-civil/index-ui'
		    },{
		        title: 'Tipo de Doc.',
		        tabConfig: {style:'width:120px'},
		        disabled: true,
		    },{
		        title: 'Rol',
		        tabConfig: {style:'width:120px'},
		        disabled: true,
		    },{
		        title: 'Relaci&oacute;n',
		        tabConfig: {style:'width:120px'},
		        disabled: true,
		    },{
		        title: 'Tipo Contacto',
		        tabConfig: {style:'width:120px'},
		        disabled: true,
		    }],
		    listeners:{
				'tabchange':function(tabPanel, newTab, oldTab, opciones)
				{
					console.log(newTab);
					console.log('opci',baseURL,tabPanel, newTab, oldTab, opciones);
					console.log( window.location, newTab.pathName);
					if(window.location.pathname !== (baseURL + newTab.pathName))//si son diferentes cambiar
					{
						console.log('in',baseURL + newTab.pathName);
						window.location = baseURL + newTab.pathName;
					}	
				}
			   }
		});
		
		var menuActividad = Ext.create('Ext.tab.Panel', {
			autoHeight:true,
			plain: true,
			style:'background-color: #C8CED8',
		    //border:0,
		    id: 'actividadTabPanel',
		    //renderTo: document.body,
		    items: [{
		        title: 'Actividad',
		        tabConfig: {style:'width:120px'},
		        pathName: '/actividad/actividad/index-ui',
		    },{
		        title: 'Tipo de Act.',
		        tabConfig: {style:'width:120px'},
		        pathName: '/actividad/actividad-tipo/index-ui',
		    },{
		        title: 'Nivel',
		        tabConfig: {style:'width:120px'},
		        pathName: '/actividad/nivel/index-ui',
		    },{
		        title: 'Modalidad',
		        tabConfig: {style:'width:120px'},
		        pathName: '/actividad/modalidad/index-ui',
		    },{
		        title: 'Criterio',
		        tabConfig: {style:'width:120px'},
		        pathName: '/actividad/criterio/index-ui',
		    },{
		        title: 'Tarifas',
		        tabConfig: {style:'width:120px'},
		        disabled: true,
		    }],
		    listeners:{
				'tabchange':function(tabPanel, newTab, oldTab, opciones)
				{
					console.log(newTab);
					console.log('opci',baseURL,tabPanel, newTab, oldTab, opciones);
					console.log( window.location, newTab.pathName);
					if(window.location.pathname !== (baseURL + newTab.pathName))//si son diferentes cambiar
					{
						console.log('in',baseURL + newTab.pathName);
						window.location = baseURL + newTab.pathName;
					}	
				}
			}
		});
		
		var menuCalendario = Ext.create('Ext.tab.Panel', {
			autoHeight:true,
			plain: true,
			style:'background-color: #C8CED8',
			//border:0,
			id: 'calendarioTabPanel',
			//renderTo: document.body,
			items: []
		});

		var menuStock = Ext.create('Ext.tab.Panel', {
			autoHeight:true,
			plain: true,
			style:'background-color: #C8CED8',
			//border:0,
			id: 'stockTabPanel',
			//renderTo: document.body,
			items: []
		});

		var menuAporte = Ext.create('Ext.tab.Panel', {
			autoHeight:true,
			plain: true,
			style:'background-color: #C8CED8',
			//border:0,
			id: 'aporteTabPanel',
			//renderTo: document.body,
			items: []
		});

		var menuBalance = Ext.create('Ext.tab.Panel', {
			autoHeight:true,
			plain: true,
			style:'background-color: #C8CED8',
			//border:0,
			id: 'balanceTabPanel',
			//renderTo: document.body,
			items: []
		});

		var menuPresupuesto = Ext.create('Ext.tab.Panel', {
			autoHeight:true,
			plain: true,
			style:'background-color: #C8CED8',
			//border:0,
			id: 'presupuestoTabPanel',
			//renderTo: document.body,
			items: []
		});

		var menuEstadistica = Ext.create('Ext.tab.Panel', {
			autoHeight:true,
			plain: true,
			style:'background-color: #C8CED8',
			//border:0,
			id: 'estadisticaTabPanel',
			//renderTo: document.body,
			items: []
		});
		
		Ext.onReady(function(){
			
			Ext.create('Ext.container.Viewport', {
			    layout: 'border',
			    items: [
				{
				    xtype: 'container',
				region: 'north',	
				layout: 'anchor',
				height: 120,
				style: 'background-color: #C8CED8',
				items:[
				
				{
				   //title: usuario_logueado,
				   xtype: 'container',
				    //collapsible: true,
				    //style:{marginBottom: '7px'},
				    style: 'border-bottom: 3px solid white',
				    //collapsed:true,
				    //border: 0,
				    //html: usuario_logueado,
				    height: 50,
				    //maxHeight: 205,
				    layout: 'column',
				    items:[
				           {
				               xtype:'container',
				               style: 'margin: 10px 20px; color: #112D6F; font-family:verdana; font-size:20px; text-transform:uppercase;',
				               html: usuario_logueado,
				               columnWidth:.5
				           },
				           {
											xtype: 'container',
											columnWidth:.5,
										    layout: 'fit',
										    style: 'margin: 0px 5px;',
										    border: 0,
										     padding: '0 0 0 0',
										     defaultType: 'textfield',
										     items: [ 
														{	
															 xtype: 'container',
															  style: 'text-align:left',
															  padding: 10,
															  items: [{
															      xtype: 'button',
															      scale: 'small',
															      style:{float:'right'},
															      text: 'SALIR',
																	width:70,
																	//disabled: true,
																	handler: function() {
															      	window.location = logout; 
																	}
															  }]
														}
											  ]
											
										}
							/*,
										{
										    xtype: 'container',
										    flex: 1,
										    padding: '0 10 10 10',
										    layout: 'anchor',
										    defaultType: 'textfield',
										    items: Ext.create('Ext.Img', {
										        src: baseURL + '/img/prh-layout.png',
										        padding: '0 0 0 820',
										    })
									    }*/
				        ]
				},
				{
				   xtype: 'container',
				   height: 100,
				   layout: 'anchor',
				   items:[
				          {
							xtype: 'tabpanel',
							autoHeight:true,
							plain: true,
							style:'background-color: #C8CED8;',
							//border:0,
							height: 75,
							//layout: 'anchor',
							id: 'topTabPanel',
							//activeTab: 3,
							//border: false,
							buttonAlign: 'center',
							items: [{
								    title: 'Persona',
								    tabConfig: {style:'width:120px'},
								    items:[menuPersona],
								},{
								    title: 'Actividad',
								    tabConfig: {style:'width:120px'},
								    items:[menuActividad],
								},{
								    title: 'Calendario',
								    tabConfig: {style:'width:120px'},
								    items:[menuCalendario],
								    disabled: true,
								},{
								    title: 'Stock',
								    tabConfig: {style:'width:120px'},
								    items:[menuStock],
								    disabled: true,
								},{
								    title: 'Aporte',
								    tabConfig: {style:'width:120px'},
								    items:[menuAporte],
								    disabled: true,
								},{
								    title: 'Balance',
								    tabConfig: {style:'width:120px'},
								    items:[menuBalance],
								    disabled: true,
								},{
								    title: 'Presupuesto',
								    tabConfig: {style:'width:120px'},
								    items:[menuPresupuesto],
								    disabled: true,
								},{
								    title: 'Estad&iacute;stica',
								    tabConfig: {style:'width:120px'},
								    items:[menuEstadistica],
								    disabled: true,
							}]
				          }
				
				   ]
				}
				]
				},	 
			   {
			        region: 'center',
			        //anchor:'90%',
			        id: 'centerPanel',
			        autoScroll:true,
			        layout:'anchor',
			        style: 'margin-top: 5px;',
			        items:[]
    
			    }
			    ]
			});
			

		});//onready
			
		</script>
    </head>
    <body id='bodyHTML'>
       <?php echo $this->content; ?>
    </body>
</html>
		
