<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Estado Civil</title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('estadoCivil', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'org_estado_civil_id'
				},
				{
					type: 'string',
					name: 'nombre'
				}
			]
		});
		
		var estadoCivilStore = Ext.create('Ext.data.Store', {
			model: 'estadoCivil',
			pageSize: itemsPorPagina, 
			proxy: {
				type: 'ajax',
				  extraParams:{
				    	"p[limit]": itemsPorPagina,
						"p[page]": page, 
				  },
				headers: {'Accept':'application/json'},
				url: baseURL + '/org/estado-civil/index?format=json',
				reader: {
					type: 'json',
					root: 'records',
					totalProperty: 'numResults'
				}
			},
			autoLoad: true
		});

		function agregarwindow() {
			 
            var form = Ext.widget('form', {
                layout: {
                    type: 'vbox',
                    align: 'stretch'
                },
                border: false,
                bodyPadding: 10,

                fieldDefaults: {
                    labelAlign: 'top',
                    labelWidth: 100,
                    labelStyle: 'font-weight:bold'
                },
                items: [
                       {
                    xtype: 'textfield',
                    fieldLabel: 'Nombre del Estado Civil',   
                    allowBlank: false,
                    name: 'nombre',   
                }],

                buttons: [{
                    text: 'Agregar',
                    handler: function(b,e) {
                    	var basicForm = b.up('form').getForm();  						
			            var valoresForm = basicForm.getFieldValues();

			           	var auxnombre = valoresForm.nombre;
	
						Ext.Ajax.request({
							   url: baseURL + '/org/estado-civil/post',
							   success: function(response, opt){
								   Ext.Msg.show({
									    title:'Aviso',
										msg:'Estado Civil Cargado Correctamente'
								   });
								   function hide_message() {
								       Ext.defer(function() {
								           Ext.MessageBox.hide();
								       }, delay);
								   }
								   hide_message();
								   estadoCivilStore.load();
							   },
							   jsonData:{
							       'post':{
									   'nombre': auxnombre
							       }
							   }
						 });
						 this.up('window').close();
                    }
                },{
                    text: 'Cancelar',
                    handler: function() {
                        this.up('form').getForm().reset();
                        this.up('window').close();
                    }
                }]
            });

            win = Ext.widget('window', {
                title: 'Agregar Estado Civil',
                closeAction: 'hide',
                width: 400,
                height: 150,
                layout: 'fit',
                resizable: true,
                modal: true,
                items: form
            }); 
       	 win.show();
    	}  

		function editarwindow (id_edit, nombre_edit) {
			 
            var form = Ext.widget('form', {
                layout: {
                    type: 'vbox',
                    align: 'stretch'
                },
                border: false,
                bodyPadding: 10,

                fieldDefaults: {
                    labelAlign: 'top',
                    labelWidth: 100,
                    labelStyle: 'font-weight:bold'
                },
                items: [
                       {
                    xtype: 'textfield',
                    fieldLabel: 'Nombre del Estado Civil',   
                    allowBlank: false,
                    value: nombre_edit,
                    name: 'nombre',   
                }],

                buttons: [{
                    text: 'Guardar',
                    handler: function(b,e) {
                    	var basicForm = b.up('form').getForm();  						
			            var valoresForm = basicForm.getFieldValues();

			           	var auxnombre = valoresForm.nombre;
	
						Ext.Ajax.request({
							   url: baseURL + '/org/estado_civil/put',
							   success: function(response, opt){
								   Ext.Msg.show({
									    title:'Aviso',
										msg:'Estado Civil Modificado Correctamente'
								   });
								   function hide_message() {
								       Ext.defer(function() {
								           Ext.MessageBox.hide();
								       }, delay);
								   }
								   hide_message();
								   estadoCivilStore.load();
							   },
							   jsonData:{
							       'put':{
							    	   'org_estado_civil_id': id_edit,
									   'nombre': auxnombre
							       }
							   }
						 });
						 this.up('window').close();
                    }
                },{
                    text: 'Cancelar',
                    handler: function() {
                        this.up('form').getForm().reset();
                        this.up('window').close();
                    }
                }]
            });

            win = Ext.widget('window', {
                title: 'Editar Estado Civil',
                closeAction: 'hide',
                width: 400,
                height: 150,
                layout: 'fit',
                resizable: true,
                modal: true,
                items: form
            }); 
       	 win.show();
    	}  
    	
		var gridEstadoCivil = Ext.create('Ext.grid.Panel', {
            selModel: {
                checkOnly: true,
                injectCheckbox: 1
            },
            width: 'fit',
            padding: '10 10 0 10',
            height: 333,
            region: 'center',  
	           dockedItems: [
	                {     
		          	     xtype: 'toolbar',
                         dock: 'top',
                         items: [
                         { 
                             xtype: 'tbfill' 
                         },{
                        	xtype: 'button',	
     			            text: 'Agregar',
     		                handler: agregarwindow,
                         }]
	                }
	                ],                       
            layout: 'fit',
            emptyText: "No existen estado_civiles cargadas",
            
            store: estadoCivilStore,
            loadMask: true,
            // grid columns
            columns:[{
                text: "Estado Civil",
                dataIndex: 'nombre',
                align: 'left',
                flex: 1,
            },{
                xtype:'actioncolumn',
                width:35,
                align: 'center',
                items: [{
                    icon: baseURL+'/img/icons/grid/edit.png',  
                    //tooltip: 'Edit',
                handler: function(grid, rowIndex, colIndex) {
                    	var id_edit = estadoCivilStore.getAt(rowIndex).get('org_estado_civil_id');
                    	var nombre_edit = estadoCivilStore.getAt(rowIndex).get('nombre');
						editarwindow(id_edit, nombre_edit);                        
                    }
                }]
            },{
                xtype:'actioncolumn',
                width: 35,
                align: 'center',
                items: [{
                	icon: baseURL+'/img/icons/grid/delete.png',  
                    //tooltip: 'Delete',
                    handler: function(grid, rowIndex, colIndex) {
                    	var id_delete = estadoCivilStore.getAt(rowIndex).get('org_estado_civil_id');
                    	var nombre_delete = estadoCivilStore.getAt(rowIndex).get('nombre');
                    	var auxmensaje = 'Confirma que desea borrar el Estado Civil '+nombre_delete+'?';
                    	Ext.Msg.show({
                            title:'Consulta',
                            msg: auxmensaje,
                            width: 250,
                            buttons: Ext.Msg.YESNO,
                            icon: Ext.Msg.QUESTION,
                            fn: function(rec) {
                               if (rec === "yes") {
                            	   Ext.Ajax.request({
        							   url: baseURL + '/org/estado_civil/delete',
        							   success: function(response, opt){
        								   Ext.Msg.show({
        									    title:'Aviso',
        										msg:'Estado Civil Borrado Correctamente'
        								   });
        								   function hide_message() {
        								       Ext.defer(function() {
        								           Ext.MessageBox.hide();
        								       }, delay);
        								   }
        								   hide_message();
        								   estadoCivilStore.load();
        							   },
        							   jsonData:{
        							       'delete':[
        							    	id_delete
        							       ]
        							   }
        						 });
                              }
                               else{
                            	   this.close();
                               }	                               
                           }
                       });

                    	
                        
                    }
                }]
            }       
            ]
            	        	
		 });

		 
			
		var pantalla = Ext.create('Ext.panel.Panel', {
			id: 'margen',
			padding: '15 5 0 5', 
		    //title: ' ',
		    width: 'fit',
		    height: 570,
		    renderTo: Ext.getBody(),
		    items:[gridEstadoCivil],
		});
			


				
});

			
		</script>
    </head>
    <body>
    </body>
</html>
