<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>PRH - Actividad - Modalidad </title>

		<style type="text/css">
		
		#margen{
				margin: 0px;
				margin-top: 110px;
		}
        </style>
        
		<script type="text/javascript">

			var baseURL = '<?=$this->basePath()?>';

			var auxcarrera = null;
			var titulo = null;
	
			var itemsPorPagina = 10;
			var page = 0;
			
Ext.onReady(function(){
				delete Ext.tip.Tip.prototype.minWidth;

		//modelos
		Ext.define('modalidad', {
			extend: 'Ext.data.Model',
			fields: [
				{
					type: 'int',
					name: 'act_modalidad_id'
				},{
					type: 'string',
					name: 'nombre'
				},{
					type: 'string',
					name: 'descripcion'
				}
			]
		});
		
		var modalidadStore = Ext.create('Ext.data.Store', {
			model: 'modalidad',
			pageSize: itemsPorPagina, 
			proxy: {
				type: 'ajax',
				  extraParams:{
				    	"p[limit]": itemsPorPagina,
						"p[page]": page, 
				  },
				headers: {'Accept':'application/json'},
				url: baseURL + '/actividad/modalidad/index?format=json',
				reader: {
					type: 'json',
					root: 'records',
					totalProperty: 'numResults'
				}
			},
			autoLoad: true
		});

		function agregarwindow() {
			 
            var form = Ext.widget('form', {
                layout: {
                    type: 'vbox',
                    align: 'stretch'
                },
                border: false,
                bodyPadding: 10,

                fieldDefaults: {
                    labelAlign: 'top',
                    labelWidth: 100,
                    labelStyle: 'font-weight:bold'
                },
                items: [
                       	{
		                    xtype: 'textfield',
		                    fieldLabel: 'Nombre de la Modalidad',   
		                    allowBlank: true,
		                    name: 'nombre',   
                		},{
		                    xtype: 'textfield',
		                    fieldLabel: 'Descripci&oacute;n de la Modalidad',   
		                    allowBlank: true,
		                    name: 'descripcion',   
                		}
                       ],

                buttons: [{
                    text: 'Agregar',
                    handler: function(b,e) {
                    	var basicForm = b.up('form').getForm();  						
			            var valoresForm = basicForm.getFieldValues();

			           	var auxnombre = valoresForm.nombre;
			           	var auxdescripcion = valoresForm.descripcion
	
						Ext.Ajax.request({
							   url: baseURL + '/actividad/modalidad/post',
							   success: function(response, opt){
								   Ext.Msg.show({
									    title:'Aviso',
										msg:'Modalidad Cargada Correctamente'
								   });
								   function hide_message() {
								       Ext.defer(function() {
								           Ext.MessageBox.hide();
								       }, delay);
								   }
								   hide_message();
								   modalidadStore.load();
							   },
							   jsonData:{
							       'post':{
									   'nombre': auxnombre,
									   'descripcion': auxdescripcion
							       }
							   }
						 });
						 this.up('window').close();
                    }
                },{
                    text: 'Cancelar',
                    handler: function() {
                        this.up('form').getForm().reset();
                        this.up('window').close();
                    }
                }]
            });

            win = Ext.widget('window', {
                title: 'Agregar Modalidad',
                closeAction: 'hide',
                width: 400,
                height: 200,
                layout: 'fit',
                resizable: true,
                modal: true,
                items: form
            }); 
       	 win.show();
    	}  

		function editarwindow (id_edit, nombre_edit, descripcion_edit) {
			 
            var form = Ext.widget('form', {
                layout: {
                    type: 'vbox',
                    align: 'stretch'
                },
                border: false,
                bodyPadding: 10,

                fieldDefaults: {
                    labelAlign: 'top',
                    labelWidth: 100,
                    labelStyle: 'font-weight:bold'
                },
                items: [
                       	{
		                    xtype: 'textfield',
		                    fieldLabel: 'Nombre de la Modalidad',   
		                    allowBlank: true,
		                    value: nombre_edit,
		                    name: 'nombre',   
                		},{
		                    xtype: 'textfield',
		                    fieldLabel: 'Descripci&oacute;n de la Modalidad',   
		                    allowBlank: true,
		                    value: descripcion_edit,
		                    name: 'descripcion',   
                		}
                ],

                buttons: [{
                    text: 'Guardar',
                    handler: function(b,e) {
                    	var basicForm = b.up('form').getForm();  						
			            var valoresForm = basicForm.getFieldValues();

			           	var auxnombre = valoresForm.nombre;
			        	var auxdescripcion = valoresForm.descripcion
	
						Ext.Ajax.request({
							   url: baseURL + '/actividad/modalidad/put',
							   success: function(response, opt){
								   Ext.Msg.show({
									    title:'Aviso',
										msg:'Modalidad Modificada Correctamente'
								   });
								   function hide_message() {
								       Ext.defer(function() {
								           Ext.MessageBox.hide();
								       }, delay);
								   }
								   hide_message();
								   modalidadStore.load();
							   },
							   jsonData:{
							       'put':{
							    	   'act_modalidad_id': id_edit,
							    	   'nombre': auxnombre,
									   'descripcion': auxdescripcion
							       }
							   }
						 });
						 this.up('window').close();
                    }
                },{
                    text: 'Cancelar',
                    handler: function() {
                        this.up('form').getForm().reset();
                        this.up('window').close();
                    }
                }]
            });

            win = Ext.widget('window', {
                title: 'Editar Modalidad',
                closeAction: 'hide',
                width: 400,
                height: 200,
                layout: 'fit',
                resizable: true,
                modal: true,
                items: form
            }); 
       	 win.show();
    	}  
    	
		var gridModalidad = Ext.create('Ext.grid.Panel', {
            selModel: {
                checkOnly: true,
                injectCheckbox: 1
            },
            width: 'fit',
            padding: '10 10 0 10',
            height: 335,
            region: 'center',  
	           dockedItems: [
	                {     
		          	     xtype: 'toolbar',
                         dock: 'top',
                         items: [
                         { 
                             xtype: 'tbfill' 
                         },{
                        	xtype: 'button',	
     			            text: 'Agregar',
     		                handler: agregarwindow,
                         }]
// 	                },{
// 	                    xtype: 'pagingtoolbar',
// 	                    store: modalidadStore, 
// 	                    dock: 'bottom',
// 	                    displayInfo: true,
// 	                    listeners: {
// 	                        'afterrender': function (component)
// 	                        {
// 	                            component.down('#refresh').hide()
// 	                        },single: true
// 	                    },
// 	                    displayMsg: 'Registro {0} al {1} de {2}',
// 	                    beforePageText: 'P&aacute;gina',
// 	                    afterPageText : 'de {0}',
// 	                    moveNext : function(){ 
// 	                   		page = page + itemsPorPagina;
// 	                   	 	this.store.currentPage++;
// 	           				modalidadStore.load({
// 		       				    params:{
// 		       				    	"p[limit]": itemsPorPagina,
// 		       						"p[page]": page,
// 		       						//"s[pe_plan_estudio_ver_id]": auxcarrera	        
// 		       				    }
// 	       					});
// 	                	 },
// 	                 	 movePrevious : function(){ 
// 	                 		page = page - itemsPorPagina;
// 							this.store.currentPage--;
// 							modalidadStore.load({
// 			   				    params:{
// 			   				    	"p[limit]": itemsPorPagina,
// 			   						"p[page]": page,
// 			   						//"s[pe_plan_estudio_ver_id]": auxcarrera	 	        
// 			   				    }
// 	   						});
// 	            		 },
// 	             		moveFirst : function(){ 
// 	             			page = 0;
// 							this.store.currentPage = 1;
// 							modalidadStore.load({
// 			   				    params:{
// 			   				    	"p[limit]": itemsPorPagina,
// 			   						"p[page]": page,
// 			   						//"s[pe_plan_estudio_ver_id]": auxcarrera	 	        
// 			   				    }
// 	   						});
// 	            	 	},
// 	            	 	moveLast : function(){                 	 	
// 	            	 		if (this.getStore().getTotalCount() % itemsPorPagina == "0"){
// 		                	 	page = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)-1)*itemsPorPagina;
// 		                	 	this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina));
// 	            	 		}
// 							else
// 							{
// 								page = parseInt(this.getStore().getTotalCount() / itemsPorPagina)*itemsPorPagina;
// 								this.store.currentPage = (parseInt(this.getStore().getTotalCount() / itemsPorPagina)+1);
// 							}
// 	            	 		modalidadStore.load({
// 			   				    params:{
// 			   				    	"p[limit]": itemsPorPagina,
// 			   						"p[page]": page,	        
// 			   				    }
// 	   						});      					
// 	            	 	},
	                }
	                ],                       
            layout: 'fit',
            emptyText: "No existen Modalidades cargadas",
            
            store: modalidadStore,
            loadMask: true,
            // grid columns
            columns:[{
	                text: "Modalidad",
	                dataIndex: 'nombre',
	                align: 'left',
                flex: 1,
            	},{
                    text: "Descripci&oacute;n",
                    dataIndex: 'descripcion',
                    align: 'left',
                    flex: 1,
                },{
                xtype:'actioncolumn',
                width:35,
                align: 'center',
                items: [{
                    icon: baseURL+'/img/icons/grid/edit.png',  
                    //tooltip: 'Edit',
                handler: function(grid, rowIndex, colIndex) {
                    	var id_edit = modalidadStore.getAt(rowIndex).get('act_modalidad_id');
                    	var nombre_edit = modalidadStore.getAt(rowIndex).get('nombre');
                    	var descripcion_edit = modalidadStore.getAt(rowIndex).get('descripcion');
						editarwindow(id_edit, nombre_edit, descripcion_edit);                        
                    }
                }]
            },{
                xtype:'actioncolumn',
                width: 35,
                align: 'center',
                items: [{
                	icon: baseURL+'/img/icons/grid/delete.png',  
                    //tooltip: 'Delete',
                    handler: function(grid, rowIndex, colIndex) {
                    	var id_delete = modalidadStore.getAt(rowIndex).get('act_modalidad_id');
                    	var nombre_delete = modalidadStore.getAt(rowIndex).get('nombre');
                    	var auxmensaje = 'Confirma que desea borrar la modalidad '+nombre_delete+'?';
                    	Ext.Msg.show({
                            title:'Consulta',
                            msg: auxmensaje,
                            width: 250,
                            buttons: Ext.Msg.YESNO,
                            icon: Ext.Msg.QUESTION,
                            fn: function(rec) {
                               if (rec === "yes") {
                            	   Ext.Ajax.request({
        							   url: baseURL + '/actividad/modalidad/delete',
        							   success: function(response, opt){
        								   Ext.Msg.show({
        									    title:'Aviso',
        										msg:'Modalidad Borrada Correctamente'
        								   });
        								   function hide_message() {
        								       Ext.defer(function() {
        								           Ext.MessageBox.hide();
        								       }, delay);
        								   }
        								   hide_message();
        								   modalidadStore.load();
        							   },
        							   jsonData:{
        							       'delete':{
												'act_modalidad_id': id_delete,
        							       }
        							   }
        						 });
                              }
                               else{
                            	   this.close();
                               }	                               
                           }
                       }); 
                    }
                }]
            }       
            ]
            	        	
		 });

		 
			
		var pantalla = Ext.create('Ext.panel.Panel', {
			//id: 'margen',
			padding: '15 5 0 5', 
		    //title: ' ',
		    width: 'fit',
		    height: 570,		    
		    items:[gridModalidad],
		    listeners:{
				'render':function(){
					Ext.getCmp('topTabPanel').setActiveTab(1);
					Ext.getCmp('personaTabPanel').setActiveTab(3);
				}
			}
		});
			
		Ext.getCmp('centerPanel').add(pantalla);

				
});

			
		</script>
    </head>
    <body>
    </body>
</html>
